#!/usr/bin/env bash
#
# THE ONE COMMAND — bring the whole NeuroPause stack up locally, with no cloud anything.
#
#   ./np-local-up.sh              services + migrations + backend, then print the desktop command
#   ./np-local-up.sh --desktop    ...and start the desktop too
#   ./np-local-up.sh --down       stop the local backend (leaves containers running)
#
# WHAT THIS DOES NOT DO, DELIBERATELY:
#   - no outbound network beyond the local docker services
#   - RAZORPAY IS INERT: the keys are explicitly BLANKED here, so billingConfigured() is false and
#     every billing call throws `billing_disabled` before a client is ever constructed. Payment is
#     ladder rung 3 and §2 #16 (payment is never authority) is still PROSE.
#   - DOES NOT REBUILD apps/desktop/out/ — that artifact carries P4-MIN and is what P1 attempt 2
#     runs against. The desktop here runs from source via electron-vite dev.
#   - does not touch the m365 send path, the CST kernel, or first-real-send.latch.
#
set -uo pipefail
cd "$(dirname "$0")"
ROOT="$PWD"
BLUE=$'\033[34m'; GREEN=$'\033[32m'; YEL=$'\033[33m'; RED=$'\033[31m'; OFF=$'\033[0m'
say()  { printf '%s==>%s %s\n' "$BLUE" "$OFF" "$*"; }
ok()   { printf '%s  ok%s %s\n' "$GREEN" "$OFF" "$*"; }
warn() { printf '%s  !!%s %s\n' "$YEL" "$OFF" "$*"; }
die()  { printf '%s FAIL%s %s\n' "$RED" "$OFF" "$*"; exit 1; }

PIDFILE="$ROOT/.np-local-backend.pid"
LOGFILE="$ROOT/.np-local-backend.log"

if [[ "${1:-}" == "--down" ]]; then
  if [[ -f "$PIDFILE" ]] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
    kill "$(cat "$PIDFILE")" && rm -f "$PIDFILE" && ok "local backend stopped"
  else
    warn "no local backend running (pidfile absent or stale)"; rm -f "$PIDFILE"
  fi
  exit 0
fi

# ── 1 · PREFLIGHT ────────────────────────────────────────────────────────────────────────────
say "preflight"
command -v docker >/dev/null || die "docker not found. Install Docker Desktop, or rule the bundling fork (see §5 of the morning report)."
docker info >/dev/null 2>&1 || die "docker is installed but not running. Start Docker Desktop."
ok "docker available"

# ── 2 · SERVICES ─────────────────────────────────────────────────────────────────────────────
say "services (postgres, redis, qdrant) via docker-compose.yml"
docker compose up -d >/dev/null 2>&1 || die "docker compose up failed"
for i in $(seq 1 30); do
  pg=$(docker exec neuropause-postgres pg_isready -U neuropause 2>/dev/null | grep -c "accepting" || true)
  rd=$(docker exec neuropause-redis redis-cli ping 2>/dev/null | grep -c PONG || true)
  [[ "$pg" == "1" && "$rd" == "1" ]] && break
  sleep 1
done
[[ "${pg:-0}" == "1" ]] || die "postgres did not become ready"
[[ "${rd:-0}" == "1" ]] || die "redis did not become ready"
ok "postgres accepting connections"
ok "redis responding to PING"

# ── 3 · LOCAL ENV ────────────────────────────────────────────────────────────────────────────
# Written to a gitignored file so a dev secret is never committed. Regenerated if absent.
ENVFILE="$ROOT/.env.local-stack"
if [[ ! -f "$ENVFILE" ]]; then
  say "generating $ENVFILE (gitignored, local dev only)"
  SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  cat > "$ENVFILE" <<EOF
# Generated by np-local-up.sh — LOCAL DEV ONLY. Gitignored. Not a production secret.
DATABASE_URL=postgres://neuropause:neuropause_dev@127.0.0.1:5432/neuropause
REDIS_URL=redis://127.0.0.1:6379
JWT_ACCESS_SECRET=$SECRET
NODE_ENV=development
LOG_LEVEL=info
# Payment stays INERT — blank keys make billingConfigured() false by construction.
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
EOF
  ok "generated a fresh local JWT secret"
else
  ok "using existing $ENVFILE"
fi
set -a; . "$ENVFILE"; set +a
[[ -z "${RAZORPAY_KEY_ID:-}" && -z "${RAZORPAY_KEY_SECRET:-}" ]] \
  || die "RAZORPAY keys are set in the local env — refusing to start. Payment must stay inert."
ok "razorpay inert (billingConfigured() will be false)"

# ── 4 · MIGRATIONS ───────────────────────────────────────────────────────────────────────────
say "migrations"
( cd apps/backend && npx tsx src/db/migrate.ts ) 2>&1 | sed 's/^/    /' | tail -3
ok "schema current"

# ── 5 · BACKEND ──────────────────────────────────────────────────────────────────────────────
# Prefer 4000 (the desktop's built-in default, so no env is needed). If something already holds it
# — e.g. a prod container — fall back and tell the desktop explicitly.
PORT_PICKED=""
for p in 4000 4010 4011 4012; do
  if ! lsof -nP -iTCP:$p -sTCP:LISTEN >/dev/null 2>&1; then PORT_PICKED=$p; break; fi
done
[[ -n "$PORT_PICKED" ]] || die "no free port among 4000/4010/4011/4012"
[[ "$PORT_PICKED" != "4000" ]] && warn "port 4000 is already in use (likely the prod container) — using $PORT_PICKED"

say "backend on :$PORT_PICKED (from source, tsx)"
# stdin/stdout/stderr are ALL detached: a background child that inherits the caller's stdout keeps
# a pipe open, so `./np-local-up.sh | tail` would hang forever after the work was already done.
cd apps/backend
PORT=$PORT_PICKED BACKEND_PORT=$PORT_PICKED \
  nohup npx tsx src/index.ts > "$LOGFILE" 2>&1 < /dev/null &
echo $! > "$PIDFILE"
cd "$ROOT"
for i in $(seq 1 30); do
  body=$(curl -s -m 2 "http://127.0.0.1:$PORT_PICKED/health" 2>/dev/null || true)
  [[ "$body" == *'"status":"ok"'* ]] && break
  sleep 1
done
[[ "$body" == *'"status":"ok"'* ]] || { tail -20 "$LOGFILE"; die "backend did not report healthy — see $LOGFILE"; }
ok "backend healthy: $body"

BACKEND_URL="http://127.0.0.1:$PORT_PICKED"

# ── 6 · DESKTOP ──────────────────────────────────────────────────────────────────────────────
echo
say "THE STACK IS UP"
cat <<EOF
    services   postgres :5432   redis :6379   qdrant :6333   (docker-compose.yml)
    backend    $BACKEND_URL/health  →  database up, redis up
    payment    INERT (no keys)
    network    local only
    logs       $LOGFILE
EOF
echo
if [[ "${1:-}" == "--desktop" ]]; then
  say "desktop (electron-vite dev — does NOT touch apps/desktop/out/)"
  NEUROPAUSE_BACKEND_URL="$BACKEND_URL" npm run dev:desktop
else
  say "to start the desktop against it:"
  echo "    NEUROPAUSE_BACKEND_URL=$BACKEND_URL npm run dev:desktop"
  echo
  echo "    (the desktop already defaults to http://127.0.0.1:4000 when unpackaged,"
  echo "     so the env var is only needed when 4000 was taken.)"
  echo
  say "to stop the backend:  ./np-local-up.sh --down"
fi
