#!/usr/bin/env node
/**
 * Third-party notices generator (Phase 8 · RC hardening 8.8).
 *
 * The packaged app redistributes Electron, Chromium, React and hundreds of
 * MIT/BSD/Apache transitive dependencies — nearly all of which require their
 * copyright notice and license text to accompany distributed binaries. Before
 * Phase 8 the repo shipped none. This script walks the desktop workspace's
 * PRODUCTION dependency tree (npm's own resolution, no new dependency) and
 * writes THIRD-PARTY-NOTICES.md twice: at the repo root (for the repository)
 * and into resources/ (bundled into the app via electron-builder
 * extraResources, surfaced from Settings → About).
 *
 * Runs as the first step of every package script, so a build can never ship
 * without current notices. Fails soft in dev (missing node_modules → clear
 * message, nonzero exit) — packaging environments always have modules.
 */
const { spawnSync } = require('node:child_process');
const { readFileSync, writeFileSync, mkdirSync, readdirSync } = require('node:fs');
const { join, dirname } = require('node:path');

const APP_DIR = join(__dirname, '..');
const REPO_ROOT = join(APP_DIR, '..', '..');

/** Production dependency tree via npm's own resolver (tolerates warnings). */
function prodTree() {
  const result = spawnSync('npm', ['ls', '--omit=dev', '--all', '--json'], {
    cwd: APP_DIR,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  const raw = (result.stdout || '').trim();
  if (!raw) {
    console.error('generate-notices: `npm ls` produced no output — run npm install first.');
    process.exit(1);
  }
  return JSON.parse(raw);
}

/** Flatten {name → {version, node_modules path?}} uniquely (first version wins). */
function collect(node, out, seenPaths) {
  const deps = node.dependencies ?? {};
  for (const [name, child] of Object.entries(deps)) {
    if (child && typeof child === 'object' && child.version) {
      const key = `${name}@${child.version}`;
      if (!out.has(key)) out.set(key, { name, version: child.version, path: child.path ?? null });
      if (!seenPaths.has(key)) {
        seenPaths.add(key);
        collect(child, out, seenPaths);
      }
    }
  }
}

function resolvePackageDir(name, hintPath) {
  if (hintPath) return hintPath;
  const candidates = [join(APP_DIR, 'node_modules', name), join(REPO_ROOT, 'node_modules', name)];
  for (const dir of candidates) {
    try {
      readFileSync(join(dir, 'package.json'));
      return dir;
    } catch {
      /* try next */
    }
  }
  return null;
}

function licenseText(dir) {
  try {
    const entry = readdirSync(dir).find((f) => /^(licen[cs]e|notice)(\.|$)/i.test(f));
    if (!entry) return null;
    const text = readFileSync(join(dir, entry), 'utf8');
    return text.length > 12_000 ? `${text.slice(0, 12_000)}\n…[truncated]` : text;
  } catch {
    return null;
  }
}

const tree = prodTree();
const found = new Map();
collect(tree, found, new Set());

const entries = [...found.values()]
  .filter((e) => !e.name.startsWith('@neuropause/')) // first-party workspaces
  .sort((a, b) => a.name.localeCompare(b.name));

const blocks = [];
for (const e of entries) {
  const dir = resolvePackageDir(e.name, e.path);
  let license = 'UNKNOWN';
  let text = null;
  if (dir) {
    try {
      const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
      license = typeof pkg.license === 'string' ? pkg.license : (pkg.license?.type ?? 'UNKNOWN');
    } catch {
      /* keep UNKNOWN */
    }
    text = licenseText(dir);
  }
  blocks.push(
    `## ${e.name}@${e.version} — ${license}\n\n` +
      (text ? '```\n' + text.trim() + '\n```' : '_License text not found in the package; see the project’s repository._'),
  );
}

const header =
  '# Third-Party Notices\n\n' +
  'NeuroPause Desktop bundles the open-source packages below (production\n' +
  'dependency closure of the desktop application, plus the Electron runtime —\n' +
  'Electron itself is MIT-licensed and embeds Chromium (BSD and other licenses)\n' +
  'and Node.js (MIT); their full license bundles ship inside the Electron\n' +
  `framework directory of the packaged app). Generated by\n` +
  '`apps/desktop/scripts/generate-notices.cjs` during packaging — do not edit\n' +
  `by hand.\n\nPackages: ${entries.length}\n\n---\n\n`;

const doc = header + blocks.join('\n\n---\n\n') + '\n';
const targets = [join(REPO_ROOT, 'THIRD-PARTY-NOTICES.md'), join(APP_DIR, 'resources', 'THIRD-PARTY-NOTICES.md')];
for (const target of targets) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, doc);
}
console.log(`generate-notices: ${entries.length} package(s) → ${targets.join(', ')}`);
