/**
 * HR → Payslips — immutable per-employee pay statements (W6-A5). A payslip is
 * a SNAPSHOT built from one POSTED payroll run's computed line for one
 * employee: itemized earnings, itemized deductions (statutory + contractual),
 * net pay, and employer contributions shown as cost-to-company (never
 * deducted from the employee). Once generated it is frozen — the `generatedAt`
 * marker makes it immutable history, exactly like the W1 aging snapshots.
 *
 * Payslips are GENERATED by the payroll run's action (one per employee, idempotent),
 * not hand-authored — this file supplies the pure builder + renderer both the
 * backend action and the tests share.
 *
 * Pure (no I/O), so it is shared by the backend hooks and the tests.
 */
import type { EnterpriseEntity, EnterpriseFieldValue } from './enterpriseModule';
import type { PayComponentLine, StatutoryPayrollLine } from './payrollProcessing';

/** The Payslips module id + record kind (the framework store key). */
export const PAYSLIPS_MODULE_ID = 'hr-payslips';
export const PAYSLIP_KIND = 'payslip';

const round2 = (n: number): number => Math.round(n * 100) / 100;
function str(v: unknown): string {
  return v === null || v === undefined ? '' : String(v);
}
function num(v: unknown): number {
  return typeof v === 'number' ? v : Number(str(v)) || 0;
}

/** The deterministic payslip identifier. */
export function payslipNumber(runNumber: string, employeeNumber: string): string {
  return `PS-${runNumber}-${employeeNumber}`;
}

/** Meta the run action supplies alongside the computed line. */
export interface PayslipMeta {
  runNumber: string;
  periodKey: string;
  employeeNumber: string;
  generatedAt: string;
}

/**
 * Build the flat field set for one payslip from a posted run's line. Statutory
 * deductions become itemized deduction lines (only when non-zero — a zero PF
 * line is not shown), followed by the contractual deductions. Totals are
 * derived, never trusted from outside; `netPay` is asserted to equal the line's.
 */
export function buildPayslipFields(line: StatutoryPayrollLine, meta: PayslipMeta): Record<string, EnterpriseFieldValue> {
  const deductions: PayComponentLine[] = [];
  if (line.pfEmployee > 0) deductions.push({ code: 'PF', name: 'Provident Fund (employee)', amount: round2(line.pfEmployee) });
  if (line.esiEmployee > 0) deductions.push({ code: 'ESI', name: 'ESI (employee)', amount: round2(line.esiEmployee) });
  if (line.pt > 0) deductions.push({ code: 'PT', name: 'Professional Tax', amount: round2(line.pt) });
  if (line.tdsMonthly > 0) deductions.push({ code: 'TDS', name: 'TDS (income tax)', amount: round2(line.tdsMonthly) });
  for (const d of line.contractualDeductions) deductions.push({ code: d.code, name: d.name, amount: round2(d.amount) });
  const totalDeductions = round2(deductions.reduce((s, d) => s + d.amount, 0));
  const grossEarnings = round2(line.earnings.reduce((s, e) => s + e.amount, 0));
  return {
    payslipNumber: payslipNumber(meta.runNumber, meta.employeeNumber),
    runNumber: meta.runNumber,
    periodKey: meta.periodKey,
    employee: line.employee,
    employeeName: line.name,
    employeeNumber: meta.employeeNumber,
    mode: line.mode,
    grossEarnings,
    earningsJson: JSON.stringify(line.earnings),
    deductionsJson: JSON.stringify(deductions),
    pfEmployee: round2(line.pfEmployee),
    esiEmployee: round2(line.esiEmployee),
    professionalTax: round2(line.pt),
    tds: round2(line.tdsMonthly),
    contractualTotal: round2(line.contractualDeductions.reduce((s, d) => s + d.amount, 0)),
    totalDeductions,
    netPay: round2(line.netPay),
    pfEmployer: round2(line.pfEmployerTotal),
    esiEmployer: round2(line.esiEmployer),
    ptSkipped: line.ptSkipped,
    generatedAt: meta.generatedAt,
    status: 'issued',
    note: line.ptSkipped ? 'Professional tax not applied — no valid work state at run time.' : '',
  };
}

/** A typed view over a payslip record's flat fields. */
export interface Payslip {
  id: string;
  payslipNumber: string;
  runNumber: string;
  periodKey: string;
  employee: string;
  employeeName: string;
  employeeNumber: string;
  mode: string;
  grossEarnings: number;
  earnings: PayComponentLine[];
  deductions: PayComponentLine[];
  pfEmployee: number;
  esiEmployee: number;
  professionalTax: number;
  tds: number;
  contractualTotal: number;
  totalDeductions: number;
  netPay: number;
  pfEmployer: number;
  esiEmployer: number;
  generatedAt: string | null;
}

function parseComponents(raw: unknown): PayComponentLine[] {
  try {
    const parsed: unknown = JSON.parse(str(raw) || '[]');
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter((v) => typeof v === 'object' && v !== null)
      .map((v) => {
        const o = v as Record<string, unknown>;
        return { code: str(o.code), name: str(o.name), amount: num(o.amount) };
      });
  } catch {
    return [];
  }
}

/** Project a framework record into a typed payslip. */
export function payslipFromRecord(record: EnterpriseEntity): Payslip {
  const f = record.fields;
  return {
    id: record.id,
    payslipNumber: str(f.payslipNumber) || record.title,
    runNumber: str(f.runNumber),
    periodKey: str(f.periodKey),
    employee: str(f.employee),
    employeeName: str(f.employeeName),
    employeeNumber: str(f.employeeNumber),
    mode: str(f.mode),
    grossEarnings: num(f.grossEarnings),
    earnings: parseComponents(f.earningsJson),
    deductions: parseComponents(f.deductionsJson),
    pfEmployee: num(f.pfEmployee),
    esiEmployee: num(f.esiEmployee),
    professionalTax: num(f.professionalTax),
    tds: num(f.tds),
    contractualTotal: num(f.contractualTotal),
    totalDeductions: num(f.totalDeductions),
    netPay: num(f.netPay),
    pfEmployer: num(f.pfEmployer),
    esiEmployer: num(f.esiEmployer),
    generatedAt: str(f.generatedAt) || null,
  };
}

const pad = (label: string, amount: number): string => `  ${label.padEnd(28)}${amount.toFixed(2).padStart(14)}`;

/** Render a deterministic, human-readable payslip text (locale-free amounts). */
export function formatPayslipText(payslip: Payslip): string {
  const lines: string[] = [
    `PAYSLIP — ${payslip.periodKey}`,
    `${payslip.employeeName} (${payslip.employeeNumber})`,
    `Run: ${payslip.runNumber}`,
    '',
    'EARNINGS',
    ...payslip.earnings.map((e) => pad(e.name, e.amount)),
    pad('Gross Earnings', payslip.grossEarnings),
    '',
    'DEDUCTIONS',
    ...(payslip.deductions.length > 0 ? payslip.deductions.map((d) => pad(d.name, d.amount)) : ['  (none)']),
    pad('Total Deductions', payslip.totalDeductions),
    '',
    pad('NET PAY', payslip.netPay),
    '',
    `Employer contributions (not deducted): PF ${payslip.pfEmployer.toFixed(2)}, ESI ${payslip.esiEmployer.toFixed(2)}`,
    payslip.generatedAt ? `Generated ${payslip.generatedAt}` : 'Draft',
  ];
  return lines.join('\n');
}
