/**
 * Manufacturing → Schedule Proposals — the persisted, VERSIONED, read-only-first governance record for a
 * routing plan. A production order proposes a schedule (mined by the routing engine, captured here inert);
 * a human drives it through a strict lifecycle — proposed → approved / rejected → committed, or superseded
 * on recalculate. Only an APPROVED proposal may commit, and commit creates the real Production Schedule
 * records (reusing that module) — so nothing persists to the shop floor without approval. Rejection needs a
 * reason; recalculate mints the next version. Every transition flows through the framework's RBAC + audit +
 * timeline. The AI explains; a human approves. Modeled on the Decision Execution Handoff governance.
 */
import type { EnterpriseModuleDescriptor, EnterpriseRecordSummary } from '@neuropause/shared';
import {
  SCHEDULE_PROPOSALS_MODULE_ID,
  SCHEDULE_PROPOSAL_KIND,
  scheduleProposalFromRecord,
  scheduleProposalTransition,
} from '@neuropause/shared';
import { EnterpriseRecordStore, defineEnterpriseModule, type EnterpriseModule } from '../../framework';
import { commitProposal, recalculateProposal } from './scheduleProposalLink';

export const APPROVE_ACTION = 'approve';
export const REJECT_ACTION = 'reject';
export const RECALCULATE_ACTION = 'recalculate';
export const COMMIT_ACTION = 'commit';

export const SCHEDULE_PROPOSAL_DESCRIPTOR: EnterpriseModuleDescriptor = {
  id: SCHEDULE_PROPOSALS_MODULE_ID,
  title: 'Schedule Proposals',
  singular: 'Schedule Proposal',
  plural: 'Schedule Proposals',
  icon: 'clock',
  description: 'Read-only, versioned routing schedules — approve before they commit real Production Schedules.',
  group: 'Manufacturing',
  titleField: 'proposalNumber',
  permissions: { read: 'manufacturing:read', write: 'manufacturing:manage' },
  actions: [
    { key: APPROVE_ACTION, label: 'Approve', icon: 'check' },
    { key: REJECT_ACTION, label: 'Reject', icon: 'close' },
    { key: RECALCULATE_ACTION, label: 'Recalculate', icon: 'refresh' },
    { key: COMMIT_ACTION, label: 'Commit Schedule', icon: 'play' },
  ],
  fields: [
    { key: 'proposalNumber', label: 'Proposal #', type: 'text', required: true, placeholder: 'SPROP-MO-1-v1' },
    { key: 'productionOrder', label: 'Production Order', type: 'text', readOnly: true },
    { key: 'product', label: 'Product', type: 'text', readOnly: true },
    { key: 'routingNumber', label: 'Routing', type: 'text', column: false, readOnly: true },
    { key: 'version', label: 'Version', type: 'number', readOnly: true },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      default: 'proposed',
      badge: true,
      filterable: true,
      options: [
        { value: 'proposed', label: 'Proposed', tone: 'orange' },
        { value: 'approved', label: 'Approved', tone: 'teal' },
        { value: 'rejected', label: 'Rejected', tone: 'pink' },
        { value: 'committed', label: 'Committed', tone: 'green' },
        { value: 'superseded', label: 'Superseded', tone: 'neutral' },
      ],
    },
    { key: 'scheduledOps', label: 'Scheduled Ops', type: 'number', readOnly: true },
    { key: 'blockedOps', label: 'Blocked Ops', type: 'number', readOnly: true },
    { key: 'lateOps', label: 'Late Ops', type: 'number', column: false, readOnly: true },
    { key: 'plannedStart', label: 'Planned Start', type: 'text', column: false, readOnly: true },
    { key: 'plannedFinish', label: 'Planned Finish', type: 'text', column: false, readOnly: true },
    { key: 'machines', label: 'Machines', type: 'text', column: false, readOnly: true },
    { key: 'selectionBasis', label: 'Machine Selection', type: 'textarea', column: false, readOnly: true },
    { key: 'operations', label: 'Operations (plan)', type: 'textarea', column: false, readOnly: true },
    { key: 'generatedBy', label: 'Generated By', type: 'text', column: false, readOnly: true },
    { key: 'generatedTime', label: 'Generated', type: 'text', column: false, readOnly: true },
    { key: 'approvedBy', label: 'Approved By', type: 'text', column: false, readOnly: true },
    { key: 'approvedAt', label: 'Approved At', type: 'text', column: false, readOnly: true },
    { key: 'rejectionReason', label: 'Rejection Reason', type: 'text', column: false },
    { key: 'rejectedBy', label: 'Rejected By', type: 'text', column: false, readOnly: true },
    { key: 'rejectedAt', label: 'Rejected At', type: 'text', column: false, readOnly: true },
    { key: 'committedBy', label: 'Committed By', type: 'text', column: false, readOnly: true },
    { key: 'committedAt', label: 'Committed At', type: 'text', column: false, readOnly: true },
    { key: 'committedSchedules', label: 'Committed Schedules', type: 'text', column: false, readOnly: true },
    { key: 'late', label: 'Late', type: 'text', column: false, readOnly: true },
  ],
};

export function createScheduleProposalModule(storePath: string): EnterpriseModule {
  const store = new EnterpriseRecordStore(storePath, SCHEDULE_PROPOSALS_MODULE_ID, SCHEDULE_PROPOSAL_KIND);

  return defineEnterpriseModule({
    descriptor: SCHEDULE_PROPOSAL_DESCRIPTOR,
    store,
    hooks: {
      summarize: async (record): Promise<EnterpriseRecordSummary> => {
        const p = scheduleProposalFromRecord(record);
        return {
          moduleId: SCHEDULE_PROPOSALS_MODULE_ID,
          recordId: record.id,
          headline: `${p.proposalNumber} · v${p.version} · ${p.status}`,
          summary:
            `Schedule proposal for ${p.productionOrder} (${p.product}) via routing ${p.routingNumber}: ` +
            `${p.scheduledOps} scheduled, ${p.blockedOps} blocked op(s). ${p.status === 'committed' ? 'Committed to real Production Schedules.' : 'Read-only until approved — nothing runs automatically.'}`,
          risk: p.blockedOps > 0 || p.late ? 'medium' : 'low',
          riskReason: p.blockedOps > 0 ? `${p.blockedOps} blocked operation(s).` : p.late ? 'Projected to finish late.' : `Proposal ${p.status}.`,
          executiveExplanation: `${p.proposalNumber} is ${p.status}; a human approves before any Production Schedule is committed.`,
          grounded: false,
          model: 'none',
        };
      },
      runAction: async (action, record, ctx) => {
        const p = scheduleProposalFromRecord(record);
        const actor = ctx.actor() ?? '';
        const now = ctx.now();
        const emitSelf = (rec: ReturnType<typeof store.update>): void => {
          const self = ctx.moduleFor(SCHEDULE_PROPOSALS_MODULE_ID);
          if (self && rec) ctx.emit(self, 'updated', rec);
        };

        // Recalculate is not a simple self-transition — it supersedes this record and mints the next version.
        if (action === RECALCULATE_ACTION) {
          if (p.status !== 'proposed' && p.status !== 'approved') return { ok: false, message: `Cannot recalculate a ${p.status} proposal.` };
          return recalculateProposal(record, ctx);
        }

        const target = scheduleProposalTransition(action as never, p.status);
        if (!target) return { ok: false, message: `Cannot ${action} a proposal that is ${p.status}.` };

        if (action === REJECT_ACTION) {
          if (!p.rejectionReason.trim()) return { ok: false, message: 'A rejection reason is required before rejecting a schedule proposal.' };
          emitSelf(store.update(record.id, { fields: { status: 'rejected', rejectedBy: actor, rejectedAt: now }, actor, now }));
          return { ok: true, message: `Rejected ${p.proposalNumber}. Nothing was committed.` };
        }

        if (action === APPROVE_ACTION) {
          emitSelf(store.update(record.id, { fields: { status: 'approved', approvedBy: actor, approvedAt: now }, actor, now }));
          return { ok: true, message: `Approved ${p.proposalNumber} — ready to commit.` };
        }

        if (action === COMMIT_ACTION) {
          const result = await commitProposal(record, ctx);
          if (!result.ok) return result;
          const ids = (result as { createdIds?: string[] }).createdIds ?? [];
          emitSelf(store.update(record.id, { fields: { status: 'committed', committedBy: actor, committedAt: now, committedSchedules: ids.join(',') }, actor, now }));
          return { ok: true, message: `Committed ${ids.length} scheduled operation(s) from ${p.proposalNumber}.` };
        }

        return { ok: false, error: `Unknown action "${action}".` };
      },
    },
  });
}
