/**
 * Seed marketplace listings — a small set of real example packages, run through
 * the real scan + sign pipeline at first launch so the marketplace is populated
 * and every published version carries a genuine signature. Honest examples; the
 * names say so.
 */
import type { SeedListing } from './marketplaceStore';

export const SEED_LISTINGS: SeedListing[] = [
  {
    kind: 'ai_worker',
    slug: 'research-analyst-worker',
    name: 'Research Analyst (Example)',
    summary: 'A read-only AI worker that summarizes projects and surfaces risks from your unified data.',
    category: 'Research',
    pricing: { model: 'free', amount: 0, currency: 'USD' },
    certified: true,
    changelog: 'Initial release.',
    manifest: {
      kind: 'ai_worker',
      name: 'Research Analyst',
      version: '1.0.0',
      entry: 'worker/researchAnalyst.js',
      permissions: ['workers:read', 'intelligence:read'],
      capabilities: ['summarize', 'risk-scan'],
      dependencies: ['@neuropause/sdk@^0.1.0'],
      network: [],
      metadata: { publisher: 'NeuroPause Labs', category: 'research' },
    },
  },
  {
    kind: 'connector',
    slug: 'github-connector',
    name: 'GitHub Connector (Example)',
    summary: 'OAuth connector that syncs repositories, issues, and pull requests into the unified data model.',
    category: 'Engineering',
    pricing: { model: 'free', amount: 0, currency: 'USD' },
    certified: true,
    changelog: 'Initial release.',
    manifest: {
      kind: 'connector',
      name: 'GitHub Connector',
      version: '1.2.0',
      entry: 'connector/github.js',
      permissions: ['connectors:manage'],
      capabilities: ['oauth', 'sync', 'network'],
      dependencies: ['@neuropause/sdk@^0.1.0'],
      network: ['api.github.com'],
      metadata: { publisher: 'NeuroPause Labs', category: 'engineering' },
    },
  },
  {
    kind: 'automation_template',
    slug: 'inbox-to-notion-automation',
    name: 'Inbox → Notion (Example)',
    summary: 'Summarize new email with AI and file it into Notion, with a Slack notification.',
    category: 'Productivity',
    pricing: { model: 'one_time', amount: 19, currency: 'USD' },
    certified: false,
    changelog: 'Initial release.',
    manifest: {
      kind: 'automation_template',
      name: 'Inbox to Notion',
      version: '0.9.0',
      entry: 'automation/inboxToNotion.json',
      permissions: ['connectors:read'],
      capabilities: ['trigger', 'summarize', 'network'],
      dependencies: [],
      network: ['api.notion.com', 'slack.com'],
      metadata: { publisher: 'Community', category: 'productivity' },
    },
  },
  {
    kind: 'enterprise_template',
    slug: 'soc2-governance-pack',
    name: 'SOC 2 Governance Pack (Example)',
    summary: 'Approval chains, compliance rules, and an executive dashboard tuned for SOC 2 readiness.',
    category: 'Governance',
    pricing: { model: 'subscription', amount: 99, currency: 'USD' },
    certified: true,
    changelog: 'Initial release.',
    manifest: {
      kind: 'enterprise_template',
      name: 'SOC 2 Governance Pack',
      version: '1.0.0',
      entry: 'enterprise/soc2.json',
      permissions: ['governance:read'],
      capabilities: ['approval-chains', 'compliance-rules', 'dashboards'],
      dependencies: [],
      network: [],
      metadata: { publisher: 'NeuroPause Labs', category: 'governance' },
    },
  },
  {
    kind: 'plugin',
    slug: 'markdown-export-plugin',
    name: 'Markdown Export (Example)',
    summary: 'A desktop plugin that exports any view to clean Markdown.',
    category: 'Utilities',
    pricing: { model: 'free', amount: 0, currency: 'USD' },
    certified: false,
    changelog: 'Initial release.',
    manifest: {
      kind: 'plugin',
      name: 'Markdown Export',
      version: '0.4.1',
      entry: 'plugin/markdownExport.js',
      permissions: ['plugins:manage'],
      capabilities: ['export'],
      dependencies: ['@neuropause/sdk@^0.1.0'],
      network: [],
      metadata: { publisher: 'Community', category: 'utilities' },
    },
  },
];
