/**
 * Canonical IPC channel names. Every renderer<->main message flows through
 * one of these. Keeping them centralized lets the preload bridge, the main
 * router, and the renderer client agree on a single contract.
 *
 * Channels are split into two registration groups: the original auth/app
 * channels (handled by the legacy router) and the runtime-core channels
 * (handled by the secure bridge). The preload allows the union of both.
 */
export const IpcChannel = {
  // ── auth/app (legacy router) ──
  AuthGetStatus: 'auth:getStatus',
  AuthLoginOAuth: 'auth:loginOAuth',
  AuthLoginEmail: 'auth:loginEmail',
  AuthRegisterEmail: 'auth:registerEmail',
  AuthLogout: 'auth:logout',
  AppGetInfo: 'app:getInfo',
  AppSetThemeSource: 'app:setThemeSource',
  AppGetThemeSource: 'app:getThemeSource',
  WindowClose: 'window:close',
  AuthStatusChanged: 'auth:statusChanged',
  ThemeChanged: 'app:themeChanged',
  MenuCommand: 'menu:command',

  // ── catalog (secure bridge → backend store API) ──
  CatalogFeatured: 'catalog:featured',
  CatalogCollections: 'catalog:collections',
  CatalogSections: 'catalog:sections',
  CatalogSearch: 'catalog:search',
  CatalogApp: 'catalog:app',
  CatalogReviews: 'catalog:reviews',
  CatalogDeveloper: 'catalog:developer',
  CatalogCategories: 'catalog:categories',
  CatalogBookmarks: 'catalog:bookmarks',
  CatalogToggleBookmark: 'catalog:toggleBookmark',
  CatalogSubmitReview: 'catalog:submitReview',
  CatalogRecommendations: 'catalog:recommendations',
  CatalogCheckUpdate: 'catalog:checkUpdate',

  // ── cloud organizations (secure bridge → backend /organizations) ──
  OrgList: 'org:list',
  OrgCreate: 'org:create',
  OrgGet: 'org:get',
  OrgUpdate: 'org:update',
  OrgMembers: 'org:members',
  OrgInvite: 'org:invite',
  OrgAcceptInvite: 'org:acceptInvite',
  OrgChangeRole: 'org:changeRole',
  OrgRemoveMember: 'org:removeMember',
  OrgWorkspaces: 'org:workspaces',
  OrgCreateWorkspace: 'org:createWorkspace',
  OrgUpdateWorkspace: 'org:updateWorkspace',
  OrgDeleteWorkspace: 'org:deleteWorkspace',

  // ── local application registry ──
  RegistryList: 'registry:list',
  RegistryGet: 'registry:get',
  RegistrySetFlags: 'registry:setFlags',
  RegistryStats: 'registry:stats',
  RegistryExport: 'registry:export',
  RegistryImport: 'registry:import',
  RegistryBackup: 'registry:backup',

  // ── NeuroPause Package Service ──
  NpsInstall: 'nps:install',
  NpsUninstall: 'nps:uninstall',
  NpsUpdate: 'nps:update',
  NpsRollback: 'nps:rollback',
  NpsRepair: 'nps:repair',
  NpsVerify: 'nps:verify',
  NpsOperations: 'nps:operations',
  NpsPause: 'nps:pause',
  NpsResume: 'nps:resume',
  NpsCancel: 'nps:cancel',

  // ── runtime ──
  RuntimeLaunch: 'runtime:launch',
  RuntimeStop: 'runtime:stop',
  RuntimeSuspend: 'runtime:suspend',
  RuntimeResume: 'runtime:resume',
  RuntimeRestart: 'runtime:restart',
  RuntimeList: 'runtime:list',
  RuntimeHealth: 'runtime:health',

  // ── permissions ──
  PermsList: 'perms:list',
  PermsGrant: 'perms:grant',
  PermsRevoke: 'perms:revoke',

  // ── plugin runtime ──
  PluginsList: 'plugins:list',
  PluginsGet: 'plugins:get',
  PluginsInstall: 'plugins:install',
  PluginsEnable: 'plugins:enable',
  PluginsDisable: 'plugins:disable',
  PluginsReload: 'plugins:reload',
  PluginsUpdate: 'plugins:update',
  PluginsRemove: 'plugins:remove',
  PluginsGrant: 'plugins:grant',
  PluginsRevoke: 'plugins:revoke',
  /** Plugin SDK v2 (P3.0) — list the extensions installed plugins have registered. */
  PluginsExtensions: 'plugins:extensions',
  PluginsContributions: 'plugins:contributions',

  // ── runtime-core broadcasts (main → renderer) ──
  RuntimeEventBroadcast: 'runtime:event',
  RuntimeOpenApp: 'runtime:openApp',
  NpsProgress: 'nps:progress',
  PluginEventBroadcast: 'plugins:event',

  // ── platform core (event bus / timeline / diagnostics) ──
  PlatformEmit: 'platform:emit',
  ExecutiveCenterSnapshot: 'executiveCenter:snapshot',
  DecisionList: 'decisions:list',
  DecisionCreateFromRecommendation: 'decisions:createFromRecommendation',
  DecisionSetStatus: 'decisions:setStatus',
  /** Automation Builder rule CRUD (Module 9). */
  AutomationList: 'automations:list',
  AutomationSave: 'automations:save',
  AutomationSetStatus: 'automations:setStatus',
  AutomationRemove: 'automations:remove',
  /** Automation runtime (V4.7): manual run + monitor/history. */
  AutomationRun: 'automations:run',
  AutomationMonitor: 'automations:monitor',
  AutomationHistory: 'automations:history',
  /** NeuroCore system-health snapshot (V5.0). */
  SystemHealthSnapshot: 'neurocore:systemHealth',
  /** Runtime supervisor status + history + recovery (V5.3). */
  SupervisorStatus: 'supervisor:status',
  /** Renderer reports commercial license health for NeuroCore (V6.1). */
  LicenseReportHealth: 'license:reportHealth',
  /** Create a Razorpay subscription checkout for an org+plan (V6.4). */
  BillingCheckout: 'billing:checkout',
  /** Register this device, list an org's devices, revoke a device (V6.5). */
  DevicesRegister: 'devices:register',
  DevicesList: 'devices:list',
  DevicesRevoke: 'devices:revoke',
  /** Renderer reports this device's trust status for NeuroCore (V6.5). */
  DeviceReportHealth: 'device:reportHealth',
  SupervisorHistory: 'supervisor:history',
  SupervisorRecover: 'supervisor:recover',
  SupervisorSetPolicy: 'supervisor:setPolicy',
  /** Execute Engine (V5.4). */
  ExecuteRun: 'execute:run',
  ExecuteSessions: 'execute:sessions',
  ExecuteHistory: 'execute:history',
  ExecuteCancel: 'execute:cancel',
  /** Renderer → main: live voice runtime state (V5.2). */
  VoiceStatus: 'voice:status',
  VoiceTurn: 'voice:turn',
  /** Main → renderer: tray quick-action commands (V4.0). */
  TrayCommand: 'tray:command',
  /** Runtime launch-at-login preference (V4.2). */
  RuntimeGetLoginAtStartup: 'runtime:getLoginAtStartup',
  RuntimeSetLoginAtStartup: 'runtime:setLoginAtStartup',
  TimelineQuery: 'timeline:query',
  TimelineStats: 'timeline:stats',
  TimelineExport: 'timeline:export',
  DiagnosticsGet: 'diagnostics:get',
  PlatformEventBroadcast: 'platform:event',

  // ── connector framework (NCF) ──
  ConnectorsList: 'connectors:list',
  ConnectorGet: 'connectors:get',
  ConnectorStats: 'connectors:stats',
  ConnectorConnect: 'connectors:connect',
  ConnectorDisconnect: 'connectors:disconnect',
  ConnectorReconnect: 'connectors:reconnect',
  ConnectorRefresh: 'connectors:refresh',
  ConnectorSync: 'connectors:sync',
  ConnectorHealthCheck: 'connectors:health',
  ConnectorLogs: 'connectors:logs',
  ConnectorSyncState: 'connectors:sync-state',
  ConnectorEventBroadcast: 'connectors:event',
  // P4.1 Connector Runtime v2 — operator controls (command), runtime-state read, and the
  // lifecycle (from→to transition) broadcast the Runtime Supervisor emits.
  ConnectorControl: 'connectors:control',
  ConnectorRuntime: 'connectors:runtime',
  ConnectorLifecycleBroadcast: 'connectors:lifecycle',
  /** P4.1 — the Live Connector Inspector read (runtime + per-account snapshot/health + logs + lifecycle). */
  ConnectorInspect: 'connectors:inspect',
  // P2.4 — Microsoft 365 write actions (audited, confirmation-gated) + AI drafting.
  M365ActionList: 'connectors:m365.actions',
  M365ActionExecute: 'connectors:m365.execute',
  M365Draft: 'connectors:m365.draft',

  // ── unified knowledge layer (UDM) ──
  UnifiedQuery: 'unified:query',
  UnifiedGet: 'unified:get',
  UnifiedCounts: 'unified:counts',
  UnifiedSearch: 'unified:search',
  UnifiedEventBroadcast: 'unified:event',

  // ── enterprise knowledge graph (EKG) ──
  GraphCounts: 'graph:counts',
  GraphNode: 'graph:node',
  GraphNodes: 'graph:nodes',
  GraphNeighbors: 'graph:neighbors',
  GraphSubgraph: 'graph:subgraph',
  GraphPath: 'graph:path',
  GraphHistory: 'graph:history',
  GraphRebuild: 'graph:rebuild',
  GraphEventBroadcast: 'graph:event',

  // ── AI memory + enterprise search ──
  MemoryRecall: 'memory:recall',
  MemorySemanticRecall: 'memory:semantic-recall',
  MemoryBackfill: 'memory:backfill',
  KnowledgeRelated: 'knowledge:related',
  KnowledgeTopics: 'knowledge:topics',
  KnowledgeHealth: 'knowledge:health',
  MemoryGet: 'memory:get',
  MemoryRemember: 'memory:remember',
  MemoryForget: 'memory:forget',
  MemoryCounts: 'memory:counts',
  MemoryRebuild: 'memory:rebuild',
  MemoryEventBroadcast: 'memory:event',
  // ── Executive conversation memory (Founder AI) ──
  ExecMemorySearch: 'memory:exec-search',
  ExecMemoryForget: 'memory:exec-forget',
  ExecMemoryPin: 'memory:exec-pin',
  ExecMemoryResolve: 'memory:exec-resolve',
  ExecMemoryAudit: 'memory:exec-audit',
  EnterpriseSearch: 'search:enterprise',

  // ── Enterprise timeline (unified work stream) ──
  EnterpriseTimelineQuery: 'enterpriseTimeline:query',
  EnterpriseTimelineReplay: 'enterpriseTimeline:replay',
  EnterpriseTimelineStats: 'enterpriseTimeline:stats',
  EnterpriseTimelineExport: 'enterpriseTimeline:export',
  EnterpriseTimelineEventBroadcast: 'enterpriseTimeline:event',

  // ── Daily intelligence + recommendations ──
  BriefingGenerate: 'intelligence:briefing',
  RecommendationsGenerate: 'recommendations:generate',

  // ── Founder AI ──
  FounderAsk: 'founder:ask',
  FounderAskV2: 'founder:ask-v2',
  FounderSuggestions: 'founder:suggestions',

  // ── Engineering AI ──
  EngineeringAnalyze: 'ai:engineering-analyze',

  // ── Traces (governance / context / relationship) ──
  GovernanceList: 'governance:list',
  GovernanceTrace: 'governance:trace',
  ContextTrace: 'context:trace',
  RelationshipTrace: 'relationship:trace',
  RelationshipPath: 'relationship:path',

  // ── AI Workforce ──
  WorkforceWorkers: 'workforce:workers',
  WorkforceIntelligence: 'workforce:intelligence',
  WorkforceWorkerGet: 'workforce:worker',
  WorkforceJobRun: 'workforce:job.run',
  WorkforceJobs: 'workforce:jobs',
  WorkforceJobGet: 'workforce:job',
  WorkforceProposalApprove: 'workforce:proposal.approve',
  WorkforceProposalReject: 'workforce:proposal.reject',
  WorkforceWorkflowRun: 'workforce:workflow.run',
  WorkforceWorkflowRuns: 'workforce:workflow.runs',
  WorkforceWorkflowResume: 'workforce:workflow.resume',
  WorkforceWorkflowCheckpoint: 'workforce:workflow.checkpoint',
  WorkforceAudit: 'workforce:audit',
  WorkforcePolicies: 'workforce:policies',
  WorkforceEventBroadcast: 'workforce:event',

  // ── Enterprise Operating System ──
  EnterpriseOrgGet: 'enterprise:org.get',
  EnterpriseOrgCreateUnit: 'enterprise:org.createUnit',
  EnterpriseOrgUpdateUnit: 'enterprise:org.updateUnit',
  EnterpriseOrgDeleteUnit: 'enterprise:org.deleteUnit',
  EnterpriseOrgCreateUser: 'enterprise:org.createUser',
  EnterpriseOrgUpdateUser: 'enterprise:org.updateUser',
  EnterpriseOrgDeleteUser: 'enterprise:org.deleteUser',
  EnterpriseOrgCreateRole: 'enterprise:org.createRole',
  EnterpriseOrgUpdateRole: 'enterprise:org.updateRole',
  EnterpriseOrgDeleteRole: 'enterprise:org.deleteRole',
  EnterpriseWorkspaceList: 'enterprise:workspace.list',
  EnterpriseWorkspaceActive: 'enterprise:workspace.active',
  EnterpriseWorkspaceCreate: 'enterprise:workspace.create',
  EnterpriseWorkspaceSwitch: 'enterprise:workspace.switch',
  EnterpriseGraph: 'enterprise:graph',
  EnterpriseGraphNeighbors: 'enterprise:graph.neighbors',
  EnterpriseGovernanceConfig: 'enterprise:governance.config',
  EnterpriseGovernanceCompliance: 'enterprise:governance.compliance',
  EnterpriseGovernanceSetChain: 'enterprise:governance.setChain',
  EnterpriseGovernanceSetRule: 'enterprise:governance.setRule',
  EnterpriseGovernanceAudit: 'enterprise:governance.audit',
  EnterpriseDashboard: 'enterprise:dashboard',
  /** Process Explorer — read-only projection of the mined processes (graph + filtered case list + KPIs). */
  EnterpriseProcessExplore: 'enterprise:process.explore',
  /** Process Explorer — full detail for one reconstructed case (every stage + mined recommendations). */
  EnterpriseProcessCase: 'enterprise:process.case',
  /** Production Schedule — read-only routing schedule (Gantt + KPIs + violations + governance proposals). */
  EnterpriseScheduleExplore: 'enterprise:schedule.explore',
  /** Operator Console (MES) — read-only shop-floor execution model (executions + operators + machines + quality + timeline + KPIs). */
  EnterpriseExecutionExplore: 'enterprise:execution.explore',
  /** Relationship Intelligence — read-only ERP entity relationship graph (nodes + typed edges + health/risk + KPIs + narrative). */
  EnterpriseRelationshipExplore: 'enterprise:relationship.explore',
  /** Trust Engine — read-only per-entity deterministic trust model (profiles + factors + trend + KPIs + narrative). */
  EnterpriseTrustExplore: 'enterprise:trust.explore',
  /** Context Engine (P2.5) — entity-360: unified-graph neighbors + ERP impact + timeline + memory for any entity. */
  EnterpriseContext: 'enterprise:context',
  /** Enterprise REST API (P3.0) — single gateway entrypoint: routes a REST request to an existing handler. */
  EnterpriseApiRequest: 'api:request',
  /** Enterprise REST API (P3.0) — the static route index (drives docs + OpenAPI). */
  EnterpriseApiRoutes: 'api:routes',
  /** Enterprise REST API (P3.0) — the generated OpenAPI 3.1 document (auto-synced from routes + Zod). */
  EnterpriseApiOpenApi: 'api:openapi',

  // ── Enterprise Webhooks (P3.0, Increment 4) ──
  WebhookCreate: 'webhooks:create',
  WebhookList: 'webhooks:list',
  WebhookSetEnabled: 'webhooks:setEnabled',
  WebhookDelete: 'webhooks:delete',
  WebhookDeliveries: 'webhooks:deliveries',
  WebhookDeadLetters: 'webhooks:deadLetters',
  WebhookReplay: 'webhooks:replay',
  WebhookStats: 'webhooks:stats',
  /** Broadcast on any webhook/delivery change (renderer refresh). */
  WebhookEventBroadcast: 'webhooks:event',
  // ── AI Sandbox — Sandbox Core (S1) ──
  SandboxWorkspaceList: 'sandbox:workspace.list',
  SandboxWorkspaceCreate: 'sandbox:workspace.create',
  SandboxWorkspaceUpdate: 'sandbox:workspace.update',
  SandboxWorkspaceDelete: 'sandbox:workspace.delete',
  SandboxScenarioList: 'sandbox:scenario.list',
  SandboxScenarioGet: 'sandbox:scenario.get',
  SandboxScenarioCreate: 'sandbox:scenario.create',
  SandboxScenarioUpdate: 'sandbox:scenario.update',
  SandboxScenarioArchive: 'sandbox:scenario.archive',
  SandboxScenarioVersionCreate: 'sandbox:scenario.version.create',
  SandboxScenarioVersions: 'sandbox:scenario.versions',
  SandboxExecutionEnqueue: 'sandbox:execution.enqueue',
  SandboxExecutionGet: 'sandbox:execution.get',
  SandboxExecutionHistory: 'sandbox:execution.history',
  SandboxExecutionCancel: 'sandbox:execution.cancel',
  SandboxExecutionTimeline: 'sandbox:execution.timeline',
  SandboxQueueState: 'sandbox:queue.state',
  SandboxArtifactList: 'sandbox:artifact.list',
  SandboxArtifactGet: 'sandbox:artifact.get',
  SandboxResultGet: 'sandbox:result.get',
  SandboxReportGet: 'sandbox:report.get',
  SandboxReportGenerate: 'sandbox:report.generate',
  SandboxDatasetList: 'sandbox:dataset.list',
  SandboxDatasetCreate: 'sandbox:dataset.create',
  SandboxDatasetDelete: 'sandbox:dataset.delete',
  SandboxDashboard: 'sandbox:dashboard',
  /** S6 Continuous Validation — read-only summary the Developer Portal consumes. */
  SandboxValidationSummary: 'sandbox:validation.summary',
  /** P4 Validation Experience — live dashboard projection (read). */
  SandboxValidationDashboard: 'sandbox:validation.dashboard',
  /** P4 Validation Experience — run a validation pipeline (command, gated sandbox:manage). */
  SandboxValidationRun: 'sandbox:validation.run',
  /** P4 Validation Experience — a single run + certification + regression + exports (read). */
  SandboxValidationRunGet: 'sandbox:validation.run.get',
  /** P4 Validation Experience — enable/disable a registered schedule (command, gated sandbox:manage). */
  SandboxValidationScheduleSet: 'sandbox:validation.schedule.set',
  /** Broadcast on any sandbox execution/queue change (renderer refresh). */
  SandboxEventBroadcast: 'sandbox:event',
  /** Personalization (per-user Favorites / Recently-Opened / Saved Views) — actor-scoped, persisted. */
  EnterprisePersonalizationGet: 'enterprise:personalization.get',
  EnterprisePersonalizationFavorite: 'enterprise:personalization.favorite',
  EnterprisePersonalizationRecent: 'enterprise:personalization.recent',
  EnterprisePersonalizationClearRecents: 'enterprise:personalization.clearRecents',
  EnterprisePersonalizationSaveView: 'enterprise:personalization.saveView',
  EnterprisePersonalizationDeleteView: 'enterprise:personalization.deleteView',
  EnterprisePersonalizationRenameView: 'enterprise:personalization.renameView',
  EnterpriseEventBroadcast: 'enterprise:event',

  // ── Enterprise Module Framework (ERP foundation) ──
  /** List the registered ERP modules + live record counts. */
  EnterpriseModulesList: 'enterprise:modules',
  /** Generic per-module record CRUD (module resolved from the payload). */
  EnterpriseModuleList: 'enterprise:module.list',
  EnterpriseModuleGet: 'enterprise:module.get',
  EnterpriseModuleCreate: 'enterprise:module.create',
  EnterpriseModuleUpdate: 'enterprise:module.update',
  EnterpriseModuleSetStatus: 'enterprise:module.setStatus',
  EnterpriseModuleDelete: 'enterprise:module.delete',
  EnterpriseModuleSearch: 'enterprise:module.search',
  /** AI-assisted summary + risk for one record (through the existing AI pipeline). */
  EnterpriseModuleSummarize: 'enterprise:module.summarize',
  /** Run a module-defined record action (e.g. convert a lead). */
  EnterpriseModuleAction: 'enterprise:module.action',
  /** Broadcast on any module record change (create/update/status/delete). */
  EnterpriseModuleEventBroadcast: 'enterprise:module.event',

  // ── Ecosystem Platform (Phase 8) ──
  EcosystemDeveloperDashboard: 'ecosystem:developer.dashboard',
  EcosystemDeveloperAccount: 'ecosystem:developer.account',
  EcosystemDeveloperSetPlan: 'ecosystem:developer.setPlan',
  EcosystemKeysList: 'ecosystem:keys.list',
  EcosystemKeysCreate: 'ecosystem:keys.create',
  EcosystemKeysRevoke: 'ecosystem:keys.revoke',
  /** P3.0 — rotate an API key: issue a fresh secret, revoke the old one. */
  EcosystemKeysRotate: 'ecosystem:keys.rotate',
  EcosystemOAuthList: 'ecosystem:oauth.list',
  EcosystemOAuthCreate: 'ecosystem:oauth.create',
  EcosystemOAuthDelete: 'ecosystem:oauth.delete',
  /** P3.0 — OAuth 2.1 client-credentials token endpoint (mints a Bearer access token). */
  EcosystemOAuthToken: 'ecosystem:oauth.token',
  /** P3.0 — revoke a previously-issued access token by its jti. */
  EcosystemOAuthRevokeToken: 'ecosystem:oauth.revokeToken',
  EcosystemUsageAnalytics: 'ecosystem:usage.analytics',
  EcosystemSdks: 'ecosystem:sdks',
  EcosystemMarketplaceList: 'ecosystem:marketplace.list',
  EcosystemMarketplaceDetail: 'ecosystem:marketplace.detail',
  EcosystemMarketplaceStats: 'ecosystem:marketplace.stats',
  EcosystemMarketplaceEvents: 'ecosystem:marketplace.events',
  EcosystemListingCreate: 'ecosystem:listing.create',
  EcosystemVersionCreate: 'ecosystem:listing.versionCreate',
  EcosystemListingSubmit: 'ecosystem:listing.submit',
  EcosystemListingReview: 'ecosystem:listing.review',
  EcosystemListingPublish: 'ecosystem:listing.publish',
  EcosystemListingRollback: 'ecosystem:listing.rollback',
  EcosystemListingInstall: 'ecosystem:listing.install',
  EcosystemListingRate: 'ecosystem:listing.rate',
  EcosystemGatewayVersions: 'ecosystem:gateway.versions',
  EcosystemGatewayRequest: 'ecosystem:gateway.request',
  EcosystemGatewayAudit: 'ecosystem:gateway.audit',
  EcosystemGatewayMetrics: 'ecosystem:gateway.metrics',
  EcosystemBillingSummary: 'ecosystem:billing.summary',
  EcosystemBillingPlans: 'ecosystem:billing.plans',
  EcosystemBillingSetPlan: 'ecosystem:billing.setPlan',
  EcosystemBillingInvoice: 'ecosystem:billing.invoice',
  EcosystemBillingSeats: 'ecosystem:billing.seats',
  EcosystemBillingAssignSeat: 'ecosystem:billing.assignSeat',
  EcosystemBillingReleaseSeat: 'ecosystem:billing.releaseSeat',
  EcosystemBillingLicenses: 'ecosystem:billing.licenses',
  EcosystemBillingPurchase: 'ecosystem:billing.purchase',
  EcosystemBillingPurchases: 'ecosystem:billing.purchases',

  // ── Enterprise Ecosystem (Phase 8 · Stage 2) ──
  EcosystemInstallsList: 'ecosystem:installs.list',
  EcosystemInstallsSummary: 'ecosystem:installs.summary',
  EcosystemInstall: 'ecosystem:installs.install',
  EcosystemInstallUpdate: 'ecosystem:installs.update',
  EcosystemInstallSetEnabled: 'ecosystem:installs.setEnabled',
  EcosystemUninstall: 'ecosystem:installs.uninstall',
  EcosystemShareWorker: 'ecosystem:workers.share',
  EcosystemPacksList: 'ecosystem:packs.list',
  EcosystemPacksStats: 'ecosystem:packs.stats',
  EcosystemPackPublish: 'ecosystem:packs.publish',
  EcosystemPackImport: 'ecosystem:packs.import',
  EcosystemPackRemove: 'ecosystem:packs.remove',
  EcosystemPartnersList: 'ecosystem:partners.list',
  EcosystemPartnersStats: 'ecosystem:partners.stats',
  EcosystemAnalytics: 'ecosystem:analytics',
  EcosystemEventBroadcast: 'ecosystem:event',

  // ── Cloud & Federation · Cloud Platform (Phase 9 · Stage 1) ──
  CloudRegions: 'cloud:regions',
  CloudTenants: 'cloud:tenants.list',
  CloudTenantSummary: 'cloud:tenants.summary',
  CloudCreateTenant: 'cloud:tenants.create',
  CloudSetTenantStatus: 'cloud:tenants.setStatus',
  CloudProjects: 'cloud:projects.list',
  CloudCreateProject: 'cloud:projects.create',
  CloudDeleteProject: 'cloud:projects.delete',
  CloudTeams: 'cloud:teams.list',
  CloudCreateTeam: 'cloud:teams.create',
  CloudTenantWorkers: 'cloud:tenants.workers',
  CloudStorageIsolation: 'cloud:storage.isolation',
  CloudSsoConnections: 'cloud:identity.connections',
  CloudIdentitySummary: 'cloud:identity.summary',
  CloudCreateSso: 'cloud:identity.createConnection',
  CloudUpdateSso: 'cloud:identity.updateConnection',
  CloudDeleteSso: 'cloud:identity.deleteConnection',
  CloudTestSso: 'cloud:identity.testConnection',
  CloudScim: 'cloud:identity.scim',
  CloudSetScim: 'cloud:identity.setScim',
  CloudScimSync: 'cloud:identity.scimSync',
  CloudMfa: 'cloud:identity.mfa',
  CloudSetMfa: 'cloud:identity.setMfa',
  CloudSyncStates: 'cloud:sync.states',
  CloudSyncSummary: 'cloud:sync.summary',
  CloudSyncConflicts: 'cloud:sync.conflicts',
  CloudSyncDomain: 'cloud:sync.syncDomain',
  CloudSyncAll: 'cloud:sync.syncAll',
  CloudSyncSetOnline: 'cloud:sync.setOnline',
  CloudSyncRecordChange: 'cloud:sync.recordChange',
  LiveSyncStatus: 'livesync:status',
  LiveSyncNow: 'livesync:now',
  LiveSyncSetOnline: 'livesync:setOnline',
  LiveSyncSetActiveOrg: 'livesync:setActiveOrg',
  CloudDeployments: 'cloud:api.deployments',
  CloudApiSummary: 'cloud:api.summary',
  CloudRatePolicies: 'cloud:api.policies',
  CloudSetPolicyEnabled: 'cloud:api.setPolicyEnabled',
  CloudWebhooks: 'cloud:api.webhooks',
  CloudCreateWebhook: 'cloud:api.createWebhook',
  CloudSetWebhookStatus: 'cloud:api.setWebhookStatus',
  CloudDeleteWebhook: 'cloud:api.deleteWebhook',
  CloudTestWebhook: 'cloud:api.testWebhook',
  CloudPublicApis: 'cloud:api.publicApis',
  CloudAdminOverview: 'cloud:admin.overview',
  CloudAdminCompliance: 'cloud:admin.compliance',
  CloudEventBroadcast: 'cloud:event',

  // ── Cloud & Federation · Federation Platform (Phase 9 · Stage 2) ──
  FedOrgs: 'fed:runtime.orgs',
  FedSummary: 'fed:runtime.summary',
  FedInvitations: 'fed:runtime.invitations',
  FedInviteOrg: 'fed:runtime.invite',
  FedRespondInvite: 'fed:runtime.respondInvite',
  FedTrust: 'fed:runtime.trust',
  FedSetTrust: 'fed:runtime.setTrust',
  FedShared: 'fed:runtime.shared',
  FedShareResource: 'fed:runtime.share',
  FedRevokeShare: 'fed:runtime.revokeShare',
  FedArtifacts: 'fed:exchange.artifacts',
  FedExchangeSummary: 'fed:exchange.summary',
  FedPublishArtifact: 'fed:exchange.publish',
  FedPublishVersion: 'fed:exchange.publishVersion',
  FedRateArtifact: 'fed:exchange.rate',
  FedSetVerification: 'fed:exchange.setVerification',
  FedRollbackArtifact: 'fed:exchange.rollback',
  FedInstallArtifact: 'fed:exchange.install',
  FedVerifyVersion: 'fed:exchange.verifyVersion',
  FedScopeSummary: 'fed:marketplace.scopes',
  FedSetScope: 'fed:marketplace.setScope',
  FedPolicies: 'fed:gov.policies',
  FedGovSummary: 'fed:gov.summary',
  FedAddPolicy: 'fed:gov.addPolicy',
  FedSetPolicyEnabled: 'fed:gov.setPolicyEnabled',
  FedApprovals: 'fed:gov.approvals',
  FedResolveApproval: 'fed:gov.resolveApproval',
  FedAuditTrail: 'fed:gov.audit',
  FedCompliance: 'fed:gov.compliance',
  FedRecordAction: 'fed:gov.recordAction',
  FedObservability: 'fed:obs.overview',
  FedUsageSeries: 'fed:obs.usage',
  FedSecurityEvents: 'fed:obs.security',
  FedBackups: 'fed:dr.backups',
  FedReplicas: 'fed:dr.replicas',
  FedValidations: 'fed:dr.validations',
  FedContinuity: 'fed:dr.continuity',
  FedDrSummary: 'fed:dr.summary',
  FedCreateBackup: 'fed:dr.createBackup',
  FedRunValidation: 'fed:dr.runValidation',
  FedCheckReplication: 'fed:dr.checkReplication',
  FedAdminOverview: 'fed:admin.overview',
  FedScalability: 'fed:scalability.report',
  FedEventBroadcast: 'fed:event',

  // ── application self-update (electron-updater) ──
  UpdateGetStatus: 'update:getStatus',
  UpdateCheckNow: 'update:checkNow',
  UpdateDownload: 'update:download',
  UpdateInstallOnQuit: 'update:installOnQuit',
  UpdateSetChannel: 'update:setChannel',
  UpdateEventBroadcast: 'update:event',

  // ── release engineering: migration / backup / crash / diagnostics / recovery / support ──
  MigrationStatus: 'migration:status',
  MigrationRun: 'migration:run',
  BackupList: 'backup:list',
  BackupCreate: 'backup:create',
  BackupValidate: 'backup:validate',
  BackupRestore: 'backup:restore',
  BackupDelete: 'backup:delete',
  CrashGetStatus: 'crash:getStatus',
  CrashSetOptIn: 'crash:setOptIn',
  CrashExport: 'crash:export',
  CrashRecommendations: 'crash:recommendations',
  CrashReport: 'crash:report',
  FlagsGet: 'flags:get',
  FlagsSetOverride: 'flags:setOverride',
  FlagsClearOverride: 'flags:clearOverride',
  LicenseStatus: 'license:status',
  LicenseRefresh: 'license:refresh',
  OnboardingStatus: 'onboarding:status',
  OnboardingStart: 'onboarding:start',
  OnboardingCompleteStep: 'onboarding:completeStep',
  OnboardingDismiss: 'onboarding:dismiss',
  OnboardingReset: 'onboarding:reset',
  FeedbackSubmit: 'feedback:submit',
  FeedbackList: 'feedback:list',
  FeedbackExport: 'feedback:export',
  FeedbackClear: 'feedback:clear',
  FeedbackExportToFile: 'feedback:exportToFile',
  PilotStatus: 'pilot:status',
  PilotSetEnabled: 'pilot:setEnabled',
  ReleaseDiagnosticsGet: 'releaseDiagnostics:get',
  ReleaseDiagnosticsExport: 'releaseDiagnostics:export',
  RecoverySafeModeStatus: 'recovery:safeModeStatus',
  RecoveryRun: 'recovery:run',
  SupportGenerateBundle: 'support:generateBundle',
  // P6 — Cloud & Infrastructure Control Plane (the Cloud Platform Center reads these; discovery is a manage op).
  InfraPlatforms: 'infra:platforms',
  InfraStats: 'infra:stats',
  InfraCapabilities: 'infra:capabilities',
  InfraResourceGraph: 'infra:resourceGraph',
  InfraResourceNeighbors: 'infra:resourceNeighbors',
  InfraDiscover: 'infra:discover',
  InfraActions: 'infra:actions',
  InfraAction: 'infra:action',
  InfraSearch: 'infra:search',
  InfraEventBroadcast: 'infra:event',
  // P7 — Enterprise Intelligence (read-only; RBAC-gated with intelligence:read via the SecureHandlerDef, mirroring
  // the infra: channels — hence an `intel:` namespace rather than `enterprise:`, which is reserved for the ERP
  // authz-gate registry).
  EnterpriseIntelReport: 'intel:report',
  EnterpriseIntelChangeImpact: 'intel:changeImpact',
  EnterpriseIntelRootCause: 'intel:rootCause',
} as const;

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel];

/** Legacy auth/app invokable channels (handled by ipc/router). */
export const INVOKABLE_CHANNELS: readonly IpcChannelName[] = [
  IpcChannel.AuthGetStatus,
  IpcChannel.AuthLoginOAuth,
  IpcChannel.AuthLoginEmail,
  IpcChannel.AuthRegisterEmail,
  IpcChannel.AuthLogout,
  IpcChannel.AppGetInfo,
  IpcChannel.AppSetThemeSource,
  IpcChannel.AppGetThemeSource,
  IpcChannel.WindowClose,
  IpcChannel.RuntimeGetLoginAtStartup,
  IpcChannel.RuntimeSetLoginAtStartup,
];

/** Legacy broadcasts the renderer may subscribe to. */
export const SUBSCRIBABLE_CHANNELS: readonly IpcChannelName[] = [
  IpcChannel.AuthStatusChanged,
  IpcChannel.ThemeChanged,
  IpcChannel.MenuCommand,
  IpcChannel.TrayCommand,
];

/** Runtime-core invokable channels (handled by the secure bridge). */
export const RUNTIME_INVOKABLE_CHANNELS: readonly IpcChannelName[] = [
  IpcChannel.CatalogFeatured,
  IpcChannel.CatalogCollections,
  IpcChannel.CatalogSections,
  IpcChannel.CatalogSearch,
  IpcChannel.CatalogApp,
  IpcChannel.CatalogReviews,
  IpcChannel.CatalogDeveloper,
  IpcChannel.CatalogCategories,
  IpcChannel.CatalogBookmarks,
  IpcChannel.CatalogToggleBookmark,
  IpcChannel.CatalogSubmitReview,
  IpcChannel.CatalogRecommendations,
  IpcChannel.CatalogCheckUpdate,
  IpcChannel.OrgList,
  IpcChannel.OrgCreate,
  IpcChannel.OrgGet,
  IpcChannel.OrgUpdate,
  IpcChannel.OrgMembers,
  IpcChannel.OrgInvite,
  IpcChannel.OrgAcceptInvite,
  IpcChannel.OrgChangeRole,
  IpcChannel.OrgRemoveMember,
  IpcChannel.OrgWorkspaces,
  IpcChannel.OrgCreateWorkspace,
  IpcChannel.OrgUpdateWorkspace,
  IpcChannel.OrgDeleteWorkspace,
  IpcChannel.RegistryList,
  IpcChannel.RegistryGet,
  IpcChannel.RegistrySetFlags,
  IpcChannel.RegistryStats,
  IpcChannel.RegistryExport,
  IpcChannel.RegistryImport,
  IpcChannel.RegistryBackup,
  IpcChannel.NpsInstall,
  IpcChannel.NpsUninstall,
  IpcChannel.NpsUpdate,
  IpcChannel.NpsRollback,
  IpcChannel.NpsRepair,
  IpcChannel.NpsVerify,
  IpcChannel.NpsOperations,
  IpcChannel.NpsPause,
  IpcChannel.NpsResume,
  IpcChannel.NpsCancel,
  IpcChannel.RuntimeLaunch,
  IpcChannel.RuntimeStop,
  IpcChannel.RuntimeSuspend,
  IpcChannel.RuntimeResume,
  IpcChannel.RuntimeRestart,
  IpcChannel.RuntimeList,
  IpcChannel.RuntimeHealth,
  IpcChannel.PermsList,
  IpcChannel.PermsGrant,
  IpcChannel.PermsRevoke,
  IpcChannel.PluginsList,
  IpcChannel.PluginsGet,
  IpcChannel.PluginsInstall,
  IpcChannel.PluginsEnable,
  IpcChannel.PluginsDisable,
  IpcChannel.PluginsReload,
  IpcChannel.PluginsUpdate,
  IpcChannel.PluginsRemove,
  IpcChannel.PluginsGrant,
  IpcChannel.PluginsRevoke,
  IpcChannel.PluginsExtensions,
  IpcChannel.PluginsContributions,
  IpcChannel.PlatformEmit,
  IpcChannel.ExecutiveCenterSnapshot,
  IpcChannel.DecisionList,
  IpcChannel.DecisionCreateFromRecommendation,
  IpcChannel.DecisionSetStatus,
  IpcChannel.AutomationList,
  IpcChannel.AutomationSave,
  IpcChannel.AutomationSetStatus,
  IpcChannel.AutomationRemove,
  IpcChannel.AutomationRun,
  IpcChannel.AutomationMonitor,
  IpcChannel.AutomationHistory,
  IpcChannel.SystemHealthSnapshot,
  IpcChannel.SupervisorStatus,
  IpcChannel.LicenseReportHealth,
  IpcChannel.BillingCheckout,
  IpcChannel.DevicesRegister,
  IpcChannel.DevicesList,
  IpcChannel.DevicesRevoke,
  IpcChannel.DeviceReportHealth,
  IpcChannel.SupervisorHistory,
  IpcChannel.SupervisorRecover,
  IpcChannel.SupervisorSetPolicy,
  IpcChannel.ExecuteRun,
  IpcChannel.ExecuteSessions,
  IpcChannel.ExecuteHistory,
  IpcChannel.ExecuteCancel,
  IpcChannel.VoiceStatus,
  IpcChannel.VoiceTurn,
  IpcChannel.TimelineQuery,
  IpcChannel.TimelineStats,
  IpcChannel.TimelineExport,
  IpcChannel.DiagnosticsGet,
  IpcChannel.ConnectorsList,
  IpcChannel.ConnectorGet,
  IpcChannel.ConnectorStats,
  IpcChannel.ConnectorConnect,
  IpcChannel.ConnectorDisconnect,
  IpcChannel.ConnectorReconnect,
  IpcChannel.ConnectorRefresh,
  IpcChannel.ConnectorSync,
  IpcChannel.ConnectorHealthCheck,
  IpcChannel.ConnectorLogs,
  IpcChannel.ConnectorSyncState,
  IpcChannel.ConnectorControl,
  IpcChannel.ConnectorRuntime,
  IpcChannel.ConnectorInspect,
  IpcChannel.M365ActionList,
  IpcChannel.M365ActionExecute,
  IpcChannel.M365Draft,
  IpcChannel.UnifiedQuery,
  IpcChannel.UnifiedGet,
  IpcChannel.UnifiedCounts,
  IpcChannel.UnifiedSearch,
  IpcChannel.GraphCounts,
  IpcChannel.GraphNode,
  IpcChannel.GraphNodes,
  IpcChannel.GraphNeighbors,
  IpcChannel.GraphSubgraph,
  IpcChannel.GraphPath,
  IpcChannel.GraphHistory,
  IpcChannel.GraphRebuild,
  IpcChannel.MemoryRecall,
  IpcChannel.MemorySemanticRecall,
  IpcChannel.MemoryBackfill,
  IpcChannel.KnowledgeRelated,
  IpcChannel.KnowledgeTopics,
  IpcChannel.KnowledgeHealth,
  IpcChannel.WorkforceIntelligence,
  IpcChannel.MemoryGet,
  IpcChannel.MemoryRemember,
  IpcChannel.MemoryForget,
  IpcChannel.MemoryCounts,
  IpcChannel.MemoryRebuild,
  IpcChannel.ExecMemorySearch,
  IpcChannel.ExecMemoryForget,
  IpcChannel.ExecMemoryPin,
  IpcChannel.ExecMemoryResolve,
  IpcChannel.ExecMemoryAudit,
  IpcChannel.EnterpriseSearch,
  IpcChannel.EnterpriseTimelineQuery,
  IpcChannel.EnterpriseTimelineReplay,
  IpcChannel.EnterpriseTimelineStats,
  IpcChannel.EnterpriseTimelineExport,
  IpcChannel.BriefingGenerate,
  IpcChannel.RecommendationsGenerate,
  IpcChannel.FounderAsk,
  IpcChannel.FounderAskV2,
  IpcChannel.FounderSuggestions,
  IpcChannel.EngineeringAnalyze,
  IpcChannel.GovernanceList,
  IpcChannel.GovernanceTrace,
  IpcChannel.ContextTrace,
  IpcChannel.RelationshipTrace,
  IpcChannel.RelationshipPath,
  IpcChannel.WorkforceWorkers,
  IpcChannel.WorkforceWorkerGet,
  IpcChannel.WorkforceJobRun,
  IpcChannel.WorkforceJobs,
  IpcChannel.WorkforceJobGet,
  IpcChannel.WorkforceProposalApprove,
  IpcChannel.WorkforceProposalReject,
  IpcChannel.WorkforceWorkflowRun,
  IpcChannel.WorkforceWorkflowRuns,
  IpcChannel.WorkforceWorkflowResume,
  IpcChannel.WorkforceWorkflowCheckpoint,
  IpcChannel.WorkforceAudit,
  IpcChannel.WorkforcePolicies,
  IpcChannel.EnterpriseOrgGet,
  IpcChannel.EnterpriseOrgCreateUnit,
  IpcChannel.EnterpriseOrgUpdateUnit,
  IpcChannel.EnterpriseOrgDeleteUnit,
  IpcChannel.EnterpriseOrgCreateUser,
  IpcChannel.EnterpriseOrgUpdateUser,
  IpcChannel.EnterpriseOrgDeleteUser,
  IpcChannel.EnterpriseOrgCreateRole,
  IpcChannel.EnterpriseOrgUpdateRole,
  IpcChannel.EnterpriseOrgDeleteRole,
  IpcChannel.EnterpriseWorkspaceList,
  IpcChannel.EnterpriseWorkspaceActive,
  IpcChannel.EnterpriseWorkspaceCreate,
  IpcChannel.EnterpriseWorkspaceSwitch,
  IpcChannel.EnterpriseGraph,
  IpcChannel.EnterpriseGraphNeighbors,
  IpcChannel.EnterpriseGovernanceConfig,
  IpcChannel.EnterpriseGovernanceCompliance,
  IpcChannel.EnterpriseGovernanceSetChain,
  IpcChannel.EnterpriseGovernanceSetRule,
  IpcChannel.EnterpriseGovernanceAudit,
  IpcChannel.EnterpriseDashboard,
  IpcChannel.EnterpriseProcessExplore,
  IpcChannel.EnterpriseProcessCase,
  IpcChannel.EnterpriseScheduleExplore,
  IpcChannel.EnterpriseExecutionExplore,
  IpcChannel.EnterpriseRelationshipExplore,
  IpcChannel.EnterpriseTrustExplore,
  IpcChannel.EnterpriseContext,
  IpcChannel.EnterpriseApiRequest,
  IpcChannel.EnterpriseApiRoutes,
  IpcChannel.EnterpriseApiOpenApi,
  IpcChannel.WebhookCreate,
  IpcChannel.WebhookList,
  IpcChannel.WebhookSetEnabled,
  IpcChannel.WebhookDelete,
  IpcChannel.WebhookDeliveries,
  IpcChannel.WebhookDeadLetters,
  IpcChannel.WebhookReplay,
  IpcChannel.WebhookStats,
  // AI Sandbox — Sandbox Core (S1)
  IpcChannel.SandboxWorkspaceList,
  IpcChannel.SandboxWorkspaceCreate,
  IpcChannel.SandboxWorkspaceUpdate,
  IpcChannel.SandboxWorkspaceDelete,
  IpcChannel.SandboxScenarioList,
  IpcChannel.SandboxScenarioGet,
  IpcChannel.SandboxScenarioCreate,
  IpcChannel.SandboxScenarioUpdate,
  IpcChannel.SandboxScenarioArchive,
  IpcChannel.SandboxScenarioVersionCreate,
  IpcChannel.SandboxScenarioVersions,
  IpcChannel.SandboxExecutionEnqueue,
  IpcChannel.SandboxExecutionGet,
  IpcChannel.SandboxExecutionHistory,
  IpcChannel.SandboxExecutionCancel,
  IpcChannel.SandboxExecutionTimeline,
  IpcChannel.SandboxQueueState,
  IpcChannel.SandboxArtifactList,
  IpcChannel.SandboxArtifactGet,
  IpcChannel.SandboxResultGet,
  IpcChannel.SandboxReportGet,
  IpcChannel.SandboxReportGenerate,
  IpcChannel.SandboxDatasetList,
  IpcChannel.SandboxDatasetCreate,
  IpcChannel.SandboxDatasetDelete,
  IpcChannel.SandboxDashboard,
  // AI Sandbox — Continuous Validation (S6 summary + P4 Validation Experience seams)
  IpcChannel.SandboxValidationSummary,
  IpcChannel.SandboxValidationDashboard,
  IpcChannel.SandboxValidationRun,
  IpcChannel.SandboxValidationRunGet,
  IpcChannel.SandboxValidationScheduleSet,
  IpcChannel.EnterprisePersonalizationGet,
  IpcChannel.EnterprisePersonalizationFavorite,
  IpcChannel.EnterprisePersonalizationRecent,
  IpcChannel.EnterprisePersonalizationClearRecents,
  IpcChannel.EnterprisePersonalizationSaveView,
  IpcChannel.EnterprisePersonalizationDeleteView,
  IpcChannel.EnterprisePersonalizationRenameView,
  IpcChannel.EnterpriseModulesList,
  IpcChannel.EnterpriseModuleList,
  IpcChannel.EnterpriseModuleGet,
  IpcChannel.EnterpriseModuleCreate,
  IpcChannel.EnterpriseModuleUpdate,
  IpcChannel.EnterpriseModuleSetStatus,
  IpcChannel.EnterpriseModuleDelete,
  IpcChannel.EnterpriseModuleSearch,
  IpcChannel.EnterpriseModuleSummarize,
  IpcChannel.EnterpriseModuleAction,

  // ── Ecosystem Platform ──
  IpcChannel.EcosystemDeveloperDashboard,
  IpcChannel.EcosystemDeveloperAccount,
  IpcChannel.EcosystemDeveloperSetPlan,
  IpcChannel.EcosystemKeysList,
  IpcChannel.EcosystemKeysCreate,
  IpcChannel.EcosystemKeysRevoke,
  IpcChannel.EcosystemKeysRotate,
  IpcChannel.EcosystemOAuthList,
  IpcChannel.EcosystemOAuthCreate,
  IpcChannel.EcosystemOAuthDelete,
  IpcChannel.EcosystemOAuthToken,
  IpcChannel.EcosystemOAuthRevokeToken,
  IpcChannel.EcosystemUsageAnalytics,
  IpcChannel.EcosystemSdks,
  IpcChannel.EcosystemMarketplaceList,
  IpcChannel.EcosystemMarketplaceDetail,
  IpcChannel.EcosystemMarketplaceStats,
  IpcChannel.EcosystemMarketplaceEvents,
  IpcChannel.EcosystemListingCreate,
  IpcChannel.EcosystemVersionCreate,
  IpcChannel.EcosystemListingSubmit,
  IpcChannel.EcosystemListingReview,
  IpcChannel.EcosystemListingPublish,
  IpcChannel.EcosystemListingRollback,
  IpcChannel.EcosystemListingInstall,
  IpcChannel.EcosystemListingRate,
  IpcChannel.EcosystemGatewayVersions,
  IpcChannel.EcosystemGatewayRequest,
  IpcChannel.EcosystemGatewayAudit,
  IpcChannel.EcosystemGatewayMetrics,
  IpcChannel.EcosystemBillingSummary,
  IpcChannel.EcosystemBillingPlans,
  IpcChannel.EcosystemBillingSetPlan,
  IpcChannel.EcosystemBillingInvoice,
  IpcChannel.EcosystemBillingSeats,
  IpcChannel.EcosystemBillingAssignSeat,
  IpcChannel.EcosystemBillingReleaseSeat,
  IpcChannel.EcosystemBillingLicenses,
  IpcChannel.EcosystemBillingPurchase,
  IpcChannel.EcosystemBillingPurchases,

  // ── Enterprise Ecosystem (Stage 2) ──
  IpcChannel.EcosystemInstallsList,
  IpcChannel.EcosystemInstallsSummary,
  IpcChannel.EcosystemInstall,
  IpcChannel.EcosystemInstallUpdate,
  IpcChannel.EcosystemInstallSetEnabled,
  IpcChannel.EcosystemUninstall,
  IpcChannel.EcosystemShareWorker,
  IpcChannel.EcosystemPacksList,
  IpcChannel.EcosystemPacksStats,
  IpcChannel.EcosystemPackPublish,
  IpcChannel.EcosystemPackImport,
  IpcChannel.EcosystemPackRemove,
  IpcChannel.EcosystemPartnersList,
  IpcChannel.EcosystemPartnersStats,
  IpcChannel.EcosystemAnalytics,

  // ── Cloud Platform (Stage 1) ──
  IpcChannel.CloudRegions,
  IpcChannel.CloudTenants,
  IpcChannel.CloudTenantSummary,
  IpcChannel.CloudCreateTenant,
  IpcChannel.CloudSetTenantStatus,
  IpcChannel.CloudProjects,
  IpcChannel.CloudCreateProject,
  IpcChannel.CloudDeleteProject,
  IpcChannel.CloudTeams,
  IpcChannel.CloudCreateTeam,
  IpcChannel.CloudTenantWorkers,
  IpcChannel.CloudStorageIsolation,
  IpcChannel.CloudSsoConnections,
  IpcChannel.CloudIdentitySummary,
  IpcChannel.CloudCreateSso,
  IpcChannel.CloudUpdateSso,
  IpcChannel.CloudDeleteSso,
  IpcChannel.CloudTestSso,
  IpcChannel.CloudScim,
  IpcChannel.CloudSetScim,
  IpcChannel.CloudScimSync,
  IpcChannel.CloudMfa,
  IpcChannel.CloudSetMfa,
  IpcChannel.CloudSyncStates,
  IpcChannel.CloudSyncSummary,
  IpcChannel.CloudSyncConflicts,
  IpcChannel.CloudSyncDomain,
  IpcChannel.CloudSyncAll,
  IpcChannel.CloudSyncSetOnline,
  IpcChannel.CloudSyncRecordChange,
  IpcChannel.LiveSyncStatus,
  IpcChannel.LiveSyncNow,
  IpcChannel.LiveSyncSetOnline,
  IpcChannel.LiveSyncSetActiveOrg,
  IpcChannel.CloudDeployments,
  IpcChannel.CloudApiSummary,
  IpcChannel.CloudRatePolicies,
  IpcChannel.CloudSetPolicyEnabled,
  IpcChannel.CloudWebhooks,
  IpcChannel.CloudCreateWebhook,
  IpcChannel.CloudSetWebhookStatus,
  IpcChannel.CloudDeleteWebhook,
  IpcChannel.CloudTestWebhook,
  IpcChannel.CloudPublicApis,
  IpcChannel.CloudAdminOverview,
  IpcChannel.CloudAdminCompliance,

  // ── Federation Platform (Stage 2) ──
  IpcChannel.FedOrgs,
  IpcChannel.FedSummary,
  IpcChannel.FedInvitations,
  IpcChannel.FedInviteOrg,
  IpcChannel.FedRespondInvite,
  IpcChannel.FedTrust,
  IpcChannel.FedSetTrust,
  IpcChannel.FedShared,
  IpcChannel.FedShareResource,
  IpcChannel.FedRevokeShare,
  IpcChannel.FedArtifacts,
  IpcChannel.FedExchangeSummary,
  IpcChannel.FedPublishArtifact,
  IpcChannel.FedPublishVersion,
  IpcChannel.FedRateArtifact,
  IpcChannel.FedSetVerification,
  IpcChannel.FedRollbackArtifact,
  IpcChannel.FedInstallArtifact,
  IpcChannel.FedVerifyVersion,
  IpcChannel.FedScopeSummary,
  IpcChannel.FedSetScope,
  IpcChannel.FedPolicies,
  IpcChannel.FedGovSummary,
  IpcChannel.FedAddPolicy,
  IpcChannel.FedSetPolicyEnabled,
  IpcChannel.FedApprovals,
  IpcChannel.FedResolveApproval,
  IpcChannel.FedAuditTrail,
  IpcChannel.FedCompliance,
  IpcChannel.FedRecordAction,
  IpcChannel.FedObservability,
  IpcChannel.FedUsageSeries,
  IpcChannel.FedSecurityEvents,
  IpcChannel.FedBackups,
  IpcChannel.FedReplicas,
  IpcChannel.FedValidations,
  IpcChannel.FedContinuity,
  IpcChannel.FedDrSummary,
  IpcChannel.FedCreateBackup,
  IpcChannel.FedRunValidation,
  IpcChannel.FedCheckReplication,
  IpcChannel.FedAdminOverview,
  IpcChannel.FedScalability,
  IpcChannel.UpdateGetStatus,
  IpcChannel.UpdateCheckNow,
  IpcChannel.UpdateDownload,
  IpcChannel.UpdateInstallOnQuit,
  IpcChannel.UpdateSetChannel,
  IpcChannel.MigrationStatus,
  IpcChannel.MigrationRun,
  IpcChannel.BackupList,
  IpcChannel.BackupCreate,
  IpcChannel.BackupValidate,
  IpcChannel.BackupRestore,
  IpcChannel.BackupDelete,
  IpcChannel.CrashGetStatus,
  IpcChannel.CrashSetOptIn,
  IpcChannel.CrashExport,
  IpcChannel.CrashRecommendations,
  IpcChannel.CrashReport,
  IpcChannel.FlagsGet,
  IpcChannel.FlagsSetOverride,
  IpcChannel.FlagsClearOverride,
  IpcChannel.LicenseStatus,
  IpcChannel.LicenseRefresh,
  IpcChannel.OnboardingStatus,
  IpcChannel.OnboardingStart,
  IpcChannel.OnboardingCompleteStep,
  IpcChannel.OnboardingDismiss,
  IpcChannel.OnboardingReset,
  IpcChannel.FeedbackSubmit,
  IpcChannel.FeedbackList,
  IpcChannel.FeedbackExport,
  IpcChannel.FeedbackClear,
  IpcChannel.FeedbackExportToFile,
  IpcChannel.PilotStatus,
  IpcChannel.PilotSetEnabled,
  IpcChannel.ReleaseDiagnosticsGet,
  IpcChannel.ReleaseDiagnosticsExport,
  IpcChannel.RecoverySafeModeStatus,
  IpcChannel.RecoveryRun,
  IpcChannel.SupportGenerateBundle,
  // P6 — Cloud & Infrastructure Control Plane.
  IpcChannel.InfraPlatforms,
  IpcChannel.InfraStats,
  IpcChannel.InfraCapabilities,
  IpcChannel.InfraResourceGraph,
  IpcChannel.InfraResourceNeighbors,
  IpcChannel.InfraDiscover,
  IpcChannel.InfraActions,
  IpcChannel.InfraAction,
  IpcChannel.InfraSearch,
  // P7 — Enterprise Intelligence.
  IpcChannel.EnterpriseIntelReport,
  IpcChannel.EnterpriseIntelChangeImpact,
  IpcChannel.EnterpriseIntelRootCause,
];

/** Runtime-core broadcasts. */
export const RUNTIME_BROADCAST_CHANNELS: readonly IpcChannelName[] = [
  IpcChannel.RuntimeEventBroadcast,
  IpcChannel.RuntimeOpenApp,
  IpcChannel.NpsProgress,
  IpcChannel.PluginEventBroadcast,
  IpcChannel.PlatformEventBroadcast,
  IpcChannel.ConnectorEventBroadcast,
  // Main broadcasts live sync snapshots on this channel (unified/sync/index.ts); the Connector Health
  // dashboard + Entra panel subscribe to it, so it must be on the subscribe allowlist too (it is also an
  // invokable request channel for the initial pull).
  IpcChannel.ConnectorSyncState,
  IpcChannel.ConnectorLifecycleBroadcast,
  IpcChannel.UnifiedEventBroadcast,
  IpcChannel.GraphEventBroadcast,
  IpcChannel.MemoryEventBroadcast,
  IpcChannel.EnterpriseTimelineEventBroadcast,
  IpcChannel.WorkforceEventBroadcast,
  IpcChannel.EnterpriseEventBroadcast,
  IpcChannel.EnterpriseModuleEventBroadcast,
  IpcChannel.EcosystemEventBroadcast,
  IpcChannel.CloudEventBroadcast,
  IpcChannel.FedEventBroadcast,
  IpcChannel.UpdateEventBroadcast,
  IpcChannel.WebhookEventBroadcast,
  IpcChannel.SandboxEventBroadcast,
  IpcChannel.InfraEventBroadcast,
];

/** The full set the preload bridge permits (legacy + runtime core). */
export const ALL_INVOKABLE_CHANNELS: readonly IpcChannelName[] = [
  ...INVOKABLE_CHANNELS,
  ...RUNTIME_INVOKABLE_CHANNELS,
];

export const ALL_SUBSCRIBABLE_CHANNELS: readonly IpcChannelName[] = [
  ...SUBSCRIBABLE_CHANNELS,
  ...RUNTIME_BROADCAST_CHANNELS,
];
