/**
 * Canonical IPC channel names. Every renderer<->main message flows through
 * one of these. Keeping them centralized lets the preload bridge, the main
 * router, and the renderer client agree on a single contract.
 *
 * Channels are split into two registration groups: the original auth/app
 * channels (handled by the legacy router) and the runtime-core channels
 * (handled by the secure bridge). The preload allows the union of both.
 */
export const IpcChannel = {
  // ── auth/app (legacy router) ──
  AuthGetStatus: 'auth:getStatus',
  AuthLoginOAuth: 'auth:loginOAuth',
  AuthLoginEmail: 'auth:loginEmail',
  AuthRegisterEmail: 'auth:registerEmail',
  AuthLogout: 'auth:logout',
  AppGetInfo: 'app:getInfo',
  AppSetThemeSource: 'app:setThemeSource',
  AppGetThemeSource: 'app:getThemeSource',
  WindowClose: 'window:close',
  AuthStatusChanged: 'auth:statusChanged',
  ThemeChanged: 'app:themeChanged',
  MenuCommand: 'menu:command',

  // ── catalog (secure bridge → backend store API) ──
  CatalogFeatured: 'catalog:featured',
  CatalogCollections: 'catalog:collections',
  CatalogSections: 'catalog:sections',
  CatalogSearch: 'catalog:search',
  CatalogApp: 'catalog:app',
  CatalogReviews: 'catalog:reviews',
  CatalogDeveloper: 'catalog:developer',
  CatalogCategories: 'catalog:categories',
  CatalogBookmarks: 'catalog:bookmarks',
  CatalogToggleBookmark: 'catalog:toggleBookmark',
  CatalogSubmitReview: 'catalog:submitReview',
  CatalogRecommendations: 'catalog:recommendations',
  CatalogCheckUpdate: 'catalog:checkUpdate',

  // ── cloud organizations (secure bridge → backend /organizations) ──
  OrgList: 'org:list',
  OrgCreate: 'org:create',
  OrgGet: 'org:get',
  OrgUpdate: 'org:update',
  OrgMembers: 'org:members',
  OrgInvite: 'org:invite',
  OrgAcceptInvite: 'org:acceptInvite',
  OrgChangeRole: 'org:changeRole',
  OrgRemoveMember: 'org:removeMember',
  OrgWorkspaces: 'org:workspaces',
  OrgCreateWorkspace: 'org:createWorkspace',
  OrgUpdateWorkspace: 'org:updateWorkspace',
  OrgDeleteWorkspace: 'org:deleteWorkspace',

  // ── local application registry ──
  RegistryList: 'registry:list',
  RegistryGet: 'registry:get',
  RegistrySetFlags: 'registry:setFlags',
  RegistryStats: 'registry:stats',
  RegistryExport: 'registry:export',
  RegistryImport: 'registry:import',
  RegistryBackup: 'registry:backup',

  // ── NeuroPause Package Service ──
  NpsInstall: 'nps:install',
  NpsUninstall: 'nps:uninstall',
  NpsUpdate: 'nps:update',
  NpsRollback: 'nps:rollback',
  NpsRepair: 'nps:repair',
  NpsVerify: 'nps:verify',
  NpsOperations: 'nps:operations',
  NpsPause: 'nps:pause',
  NpsResume: 'nps:resume',
  NpsCancel: 'nps:cancel',

  // ── runtime ──
  RuntimeLaunch: 'runtime:launch',
  RuntimeStop: 'runtime:stop',
  RuntimeSuspend: 'runtime:suspend',
  RuntimeResume: 'runtime:resume',
  RuntimeRestart: 'runtime:restart',
  RuntimeList: 'runtime:list',
  RuntimeHealth: 'runtime:health',

  // ── permissions ──
  PermsList: 'perms:list',
  PermsGrant: 'perms:grant',
  PermsRevoke: 'perms:revoke',

  // ── plugin runtime ──
  PluginsList: 'plugins:list',
  PluginsGet: 'plugins:get',
  PluginsInstall: 'plugins:install',
  PluginsEnable: 'plugins:enable',
  PluginsDisable: 'plugins:disable',
  PluginsReload: 'plugins:reload',
  PluginsUpdate: 'plugins:update',
  PluginsRemove: 'plugins:remove',
  PluginsGrant: 'plugins:grant',
  PluginsRevoke: 'plugins:revoke',
  PluginsContributions: 'plugins:contributions',

  // ── runtime-core broadcasts (main → renderer) ──
  RuntimeEventBroadcast: 'runtime:event',
  RuntimeOpenApp: 'runtime:openApp',
  NpsProgress: 'nps:progress',
  PluginEventBroadcast: 'plugins:event',

  // ── platform core (event bus / timeline / diagnostics) ──
  PlatformEmit: 'platform:emit',
  TimelineQuery: 'timeline:query',
  TimelineStats: 'timeline:stats',
  TimelineExport: 'timeline:export',
  DiagnosticsGet: 'diagnostics:get',
  PlatformEventBroadcast: 'platform:event',

  // ── connector framework (NCF) ──
  ConnectorsList: 'connectors:list',
  ConnectorGet: 'connectors:get',
  ConnectorStats: 'connectors:stats',
  ConnectorConnect: 'connectors:connect',
  ConnectorDisconnect: 'connectors:disconnect',
  ConnectorReconnect: 'connectors:reconnect',
  ConnectorRefresh: 'connectors:refresh',
  ConnectorSync: 'connectors:sync',
  ConnectorHealthCheck: 'connectors:health',
  ConnectorLogs: 'connectors:logs',
  ConnectorSyncState: 'connectors:sync-state',
  ConnectorEventBroadcast: 'connectors:event',

  // ── unified knowledge layer (UDM) ──
  UnifiedQuery: 'unified:query',
  UnifiedGet: 'unified:get',
  UnifiedCounts: 'unified:counts',
  UnifiedSearch: 'unified:search',
  UnifiedEventBroadcast: 'unified:event',

  // ── enterprise knowledge graph (EKG) ──
  GraphCounts: 'graph:counts',
  GraphNode: 'graph:node',
  GraphNodes: 'graph:nodes',
  GraphNeighbors: 'graph:neighbors',
  GraphSubgraph: 'graph:subgraph',
  GraphPath: 'graph:path',
  GraphHistory: 'graph:history',
  GraphRebuild: 'graph:rebuild',
  GraphEventBroadcast: 'graph:event',

  // ── AI memory + enterprise search ──
  MemoryRecall: 'memory:recall',
  MemoryGet: 'memory:get',
  MemoryRemember: 'memory:remember',
  MemoryForget: 'memory:forget',
  MemoryCounts: 'memory:counts',
  MemoryRebuild: 'memory:rebuild',
  MemoryEventBroadcast: 'memory:event',
  // ── Executive conversation memory (Founder AI) ──
  ExecMemorySearch: 'memory:exec-search',
  ExecMemoryForget: 'memory:exec-forget',
  ExecMemoryPin: 'memory:exec-pin',
  ExecMemoryResolve: 'memory:exec-resolve',
  ExecMemoryAudit: 'memory:exec-audit',
  EnterpriseSearch: 'search:enterprise',

  // ── Enterprise timeline (unified work stream) ──
  EnterpriseTimelineQuery: 'enterpriseTimeline:query',
  EnterpriseTimelineReplay: 'enterpriseTimeline:replay',
  EnterpriseTimelineStats: 'enterpriseTimeline:stats',
  EnterpriseTimelineExport: 'enterpriseTimeline:export',
  EnterpriseTimelineEventBroadcast: 'enterpriseTimeline:event',

  // ── Daily intelligence + recommendations ──
  BriefingGenerate: 'intelligence:briefing',
  RecommendationsGenerate: 'recommendations:generate',

  // ── Founder AI ──
  FounderAsk: 'founder:ask',
  FounderAskV2: 'founder:ask-v2',
  FounderSuggestions: 'founder:suggestions',

  // ── Engineering AI ──
  EngineeringAnalyze: 'ai:engineering-analyze',

  // ── Traces (governance / context / relationship) ──
  GovernanceList: 'governance:list',
  GovernanceTrace: 'governance:trace',
  ContextTrace: 'context:trace',
  RelationshipTrace: 'relationship:trace',
  RelationshipPath: 'relationship:path',

  // ── AI Workforce ──
  WorkforceWorkers: 'workforce:workers',
  WorkforceWorkerGet: 'workforce:worker',
  WorkforceJobRun: 'workforce:job.run',
  WorkforceJobs: 'workforce:jobs',
  WorkforceJobGet: 'workforce:job',
  WorkforceProposalApprove: 'workforce:proposal.approve',
  WorkforceProposalReject: 'workforce:proposal.reject',
  WorkforceWorkflowRun: 'workforce:workflow.run',
  WorkforceWorkflowRuns: 'workforce:workflow.runs',
  WorkforceWorkflowResume: 'workforce:workflow.resume',
  WorkforceWorkflowCheckpoint: 'workforce:workflow.checkpoint',
  WorkforceAudit: 'workforce:audit',
  WorkforcePolicies: 'workforce:policies',
  WorkforceEventBroadcast: 'workforce:event',

  // ── Enterprise Operating System ──
  EnterpriseOrgGet: 'enterprise:org.get',
  EnterpriseOrgCreateUnit: 'enterprise:org.createUnit',
  EnterpriseOrgUpdateUnit: 'enterprise:org.updateUnit',
  EnterpriseOrgDeleteUnit: 'enterprise:org.deleteUnit',
  EnterpriseOrgCreateUser: 'enterprise:org.createUser',
  EnterpriseOrgUpdateUser: 'enterprise:org.updateUser',
  EnterpriseOrgDeleteUser: 'enterprise:org.deleteUser',
  EnterpriseOrgCreateRole: 'enterprise:org.createRole',
  EnterpriseOrgUpdateRole: 'enterprise:org.updateRole',
  EnterpriseOrgDeleteRole: 'enterprise:org.deleteRole',
  EnterpriseWorkspaceList: 'enterprise:workspace.list',
  EnterpriseWorkspaceActive: 'enterprise:workspace.active',
  EnterpriseWorkspaceCreate: 'enterprise:workspace.create',
  EnterpriseWorkspaceSwitch: 'enterprise:workspace.switch',
  EnterpriseGraph: 'enterprise:graph',
  EnterpriseGraphNeighbors: 'enterprise:graph.neighbors',
  EnterpriseGovernanceConfig: 'enterprise:governance.config',
  EnterpriseGovernanceCompliance: 'enterprise:governance.compliance',
  EnterpriseGovernanceSetChain: 'enterprise:governance.setChain',
  EnterpriseGovernanceSetRule: 'enterprise:governance.setRule',
  EnterpriseGovernanceAudit: 'enterprise:governance.audit',
  EnterpriseDashboard: 'enterprise:dashboard',
  EnterpriseEventBroadcast: 'enterprise:event',

  // ── Ecosystem Platform (Phase 8) ──
  EcosystemDeveloperDashboard: 'ecosystem:developer.dashboard',
  EcosystemDeveloperAccount: 'ecosystem:developer.account',
  EcosystemDeveloperSetPlan: 'ecosystem:developer.setPlan',
  EcosystemKeysList: 'ecosystem:keys.list',
  EcosystemKeysCreate: 'ecosystem:keys.create',
  EcosystemKeysRevoke: 'ecosystem:keys.revoke',
  EcosystemOAuthList: 'ecosystem:oauth.list',
  EcosystemOAuthCreate: 'ecosystem:oauth.create',
  EcosystemOAuthDelete: 'ecosystem:oauth.delete',
  EcosystemUsageAnalytics: 'ecosystem:usage.analytics',
  EcosystemSdks: 'ecosystem:sdks',
  EcosystemMarketplaceList: 'ecosystem:marketplace.list',
  EcosystemMarketplaceDetail: 'ecosystem:marketplace.detail',
  EcosystemMarketplaceStats: 'ecosystem:marketplace.stats',
  EcosystemMarketplaceEvents: 'ecosystem:marketplace.events',
  EcosystemListingCreate: 'ecosystem:listing.create',
  EcosystemVersionCreate: 'ecosystem:listing.versionCreate',
  EcosystemListingSubmit: 'ecosystem:listing.submit',
  EcosystemListingReview: 'ecosystem:listing.review',
  EcosystemListingPublish: 'ecosystem:listing.publish',
  EcosystemListingRollback: 'ecosystem:listing.rollback',
  EcosystemListingInstall: 'ecosystem:listing.install',
  EcosystemListingRate: 'ecosystem:listing.rate',
  EcosystemGatewayVersions: 'ecosystem:gateway.versions',
  EcosystemGatewayRequest: 'ecosystem:gateway.request',
  EcosystemGatewayAudit: 'ecosystem:gateway.audit',
  EcosystemGatewayMetrics: 'ecosystem:gateway.metrics',
  EcosystemBillingSummary: 'ecosystem:billing.summary',
  EcosystemBillingPlans: 'ecosystem:billing.plans',
  EcosystemBillingSetPlan: 'ecosystem:billing.setPlan',
  EcosystemBillingInvoice: 'ecosystem:billing.invoice',
  EcosystemBillingSeats: 'ecosystem:billing.seats',
  EcosystemBillingAssignSeat: 'ecosystem:billing.assignSeat',
  EcosystemBillingReleaseSeat: 'ecosystem:billing.releaseSeat',
  EcosystemBillingLicenses: 'ecosystem:billing.licenses',
  EcosystemBillingPurchase: 'ecosystem:billing.purchase',
  EcosystemBillingPurchases: 'ecosystem:billing.purchases',

  // ── Enterprise Ecosystem (Phase 8 · Stage 2) ──
  EcosystemInstallsList: 'ecosystem:installs.list',
  EcosystemInstallsSummary: 'ecosystem:installs.summary',
  EcosystemInstall: 'ecosystem:installs.install',
  EcosystemInstallUpdate: 'ecosystem:installs.update',
  EcosystemInstallSetEnabled: 'ecosystem:installs.setEnabled',
  EcosystemUninstall: 'ecosystem:installs.uninstall',
  EcosystemShareWorker: 'ecosystem:workers.share',
  EcosystemPacksList: 'ecosystem:packs.list',
  EcosystemPacksStats: 'ecosystem:packs.stats',
  EcosystemPackPublish: 'ecosystem:packs.publish',
  EcosystemPackImport: 'ecosystem:packs.import',
  EcosystemPackRemove: 'ecosystem:packs.remove',
  EcosystemPartnersList: 'ecosystem:partners.list',
  EcosystemPartnersStats: 'ecosystem:partners.stats',
  EcosystemAnalytics: 'ecosystem:analytics',
  EcosystemEventBroadcast: 'ecosystem:event',

  // ── Cloud & Federation · Cloud Platform (Phase 9 · Stage 1) ──
  CloudRegions: 'cloud:regions',
  CloudTenants: 'cloud:tenants.list',
  CloudTenantSummary: 'cloud:tenants.summary',
  CloudCreateTenant: 'cloud:tenants.create',
  CloudSetTenantStatus: 'cloud:tenants.setStatus',
  CloudProjects: 'cloud:projects.list',
  CloudCreateProject: 'cloud:projects.create',
  CloudDeleteProject: 'cloud:projects.delete',
  CloudTeams: 'cloud:teams.list',
  CloudCreateTeam: 'cloud:teams.create',
  CloudTenantWorkers: 'cloud:tenants.workers',
  CloudStorageIsolation: 'cloud:storage.isolation',
  CloudSsoConnections: 'cloud:identity.connections',
  CloudIdentitySummary: 'cloud:identity.summary',
  CloudCreateSso: 'cloud:identity.createConnection',
  CloudUpdateSso: 'cloud:identity.updateConnection',
  CloudDeleteSso: 'cloud:identity.deleteConnection',
  CloudTestSso: 'cloud:identity.testConnection',
  CloudScim: 'cloud:identity.scim',
  CloudSetScim: 'cloud:identity.setScim',
  CloudScimSync: 'cloud:identity.scimSync',
  CloudMfa: 'cloud:identity.mfa',
  CloudSetMfa: 'cloud:identity.setMfa',
  CloudSyncStates: 'cloud:sync.states',
  CloudSyncSummary: 'cloud:sync.summary',
  CloudSyncConflicts: 'cloud:sync.conflicts',
  CloudSyncDomain: 'cloud:sync.syncDomain',
  CloudSyncAll: 'cloud:sync.syncAll',
  CloudSyncSetOnline: 'cloud:sync.setOnline',
  CloudSyncRecordChange: 'cloud:sync.recordChange',
  LiveSyncStatus: 'livesync:status',
  LiveSyncNow: 'livesync:now',
  LiveSyncSetOnline: 'livesync:setOnline',
  LiveSyncSetActiveOrg: 'livesync:setActiveOrg',
  CloudDeployments: 'cloud:api.deployments',
  CloudApiSummary: 'cloud:api.summary',
  CloudRatePolicies: 'cloud:api.policies',
  CloudSetPolicyEnabled: 'cloud:api.setPolicyEnabled',
  CloudWebhooks: 'cloud:api.webhooks',
  CloudCreateWebhook: 'cloud:api.createWebhook',
  CloudSetWebhookStatus: 'cloud:api.setWebhookStatus',
  CloudDeleteWebhook: 'cloud:api.deleteWebhook',
  CloudTestWebhook: 'cloud:api.testWebhook',
  CloudPublicApis: 'cloud:api.publicApis',
  CloudAdminOverview: 'cloud:admin.overview',
  CloudAdminCompliance: 'cloud:admin.compliance',
  CloudEventBroadcast: 'cloud:event',

  // ── Cloud & Federation · Federation Platform (Phase 9 · Stage 2) ──
  FedOrgs: 'fed:runtime.orgs',
  FedSummary: 'fed:runtime.summary',
  FedInvitations: 'fed:runtime.invitations',
  FedInviteOrg: 'fed:runtime.invite',
  FedRespondInvite: 'fed:runtime.respondInvite',
  FedTrust: 'fed:runtime.trust',
  FedSetTrust: 'fed:runtime.setTrust',
  FedShared: 'fed:runtime.shared',
  FedShareResource: 'fed:runtime.share',
  FedRevokeShare: 'fed:runtime.revokeShare',
  FedArtifacts: 'fed:exchange.artifacts',
  FedExchangeSummary: 'fed:exchange.summary',
  FedPublishArtifact: 'fed:exchange.publish',
  FedPublishVersion: 'fed:exchange.publishVersion',
  FedRateArtifact: 'fed:exchange.rate',
  FedSetVerification: 'fed:exchange.setVerification',
  FedRollbackArtifact: 'fed:exchange.rollback',
  FedInstallArtifact: 'fed:exchange.install',
  FedVerifyVersion: 'fed:exchange.verifyVersion',
  FedScopeSummary: 'fed:marketplace.scopes',
  FedSetScope: 'fed:marketplace.setScope',
  FedPolicies: 'fed:gov.policies',
  FedGovSummary: 'fed:gov.summary',
  FedAddPolicy: 'fed:gov.addPolicy',
  FedSetPolicyEnabled: 'fed:gov.setPolicyEnabled',
  FedApprovals: 'fed:gov.approvals',
  FedResolveApproval: 'fed:gov.resolveApproval',
  FedAuditTrail: 'fed:gov.audit',
  FedCompliance: 'fed:gov.compliance',
  FedRecordAction: 'fed:gov.recordAction',
  FedObservability: 'fed:obs.overview',
  FedUsageSeries: 'fed:obs.usage',
  FedSecurityEvents: 'fed:obs.security',
  FedBackups: 'fed:dr.backups',
  FedReplicas: 'fed:dr.replicas',
  FedValidations: 'fed:dr.validations',
  FedContinuity: 'fed:dr.continuity',
  FedDrSummary: 'fed:dr.summary',
  FedCreateBackup: 'fed:dr.createBackup',
  FedRunValidation: 'fed:dr.runValidation',
  FedCheckReplication: 'fed:dr.checkReplication',
  FedAdminOverview: 'fed:admin.overview',
  FedScalability: 'fed:scalability.report',
  FedEventBroadcast: 'fed:event',

  // ── application self-update (electron-updater) ──
  UpdateGetStatus: 'update:getStatus',
  UpdateCheckNow: 'update:checkNow',
  UpdateDownload: 'update:download',
  UpdateInstallOnQuit: 'update:installOnQuit',
  UpdateSetChannel: 'update:setChannel',
  UpdateEventBroadcast: 'update:event',

  // ── release engineering: migration / backup / crash / diagnostics / recovery / support ──
  MigrationStatus: 'migration:status',
  MigrationRun: 'migration:run',
  BackupList: 'backup:list',
  BackupCreate: 'backup:create',
  BackupValidate: 'backup:validate',
  BackupRestore: 'backup:restore',
  BackupDelete: 'backup:delete',
  CrashGetStatus: 'crash:getStatus',
  CrashSetOptIn: 'crash:setOptIn',
  CrashExport: 'crash:export',
  CrashRecommendations: 'crash:recommendations',
  CrashReport: 'crash:report',
  FlagsGet: 'flags:get',
  FlagsSetOverride: 'flags:setOverride',
  FlagsClearOverride: 'flags:clearOverride',
  LicenseStatus: 'license:status',
  LicenseRefresh: 'license:refresh',
  OnboardingStatus: 'onboarding:status',
  OnboardingStart: 'onboarding:start',
  OnboardingCompleteStep: 'onboarding:completeStep',
  OnboardingDismiss: 'onboarding:dismiss',
  OnboardingReset: 'onboarding:reset',
  FeedbackSubmit: 'feedback:submit',
  FeedbackList: 'feedback:list',
  FeedbackExport: 'feedback:export',
  FeedbackClear: 'feedback:clear',
  PilotStatus: 'pilot:status',
  PilotSetEnabled: 'pilot:setEnabled',
  ReleaseDiagnosticsGet: 'releaseDiagnostics:get',
  ReleaseDiagnosticsExport: 'releaseDiagnostics:export',
  RecoverySafeModeStatus: 'recovery:safeModeStatus',
  RecoveryRun: 'recovery:run',
  SupportGenerateBundle: 'support:generateBundle',
} as const;

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel];

/** Legacy auth/app invokable channels (handled by ipc/router). */
export const INVOKABLE_CHANNELS: readonly IpcChannelName[] = [
  IpcChannel.AuthGetStatus,
  IpcChannel.AuthLoginOAuth,
  IpcChannel.AuthLoginEmail,
  IpcChannel.AuthRegisterEmail,
  IpcChannel.AuthLogout,
  IpcChannel.AppGetInfo,
  IpcChannel.AppSetThemeSource,
  IpcChannel.AppGetThemeSource,
  IpcChannel.WindowClose,
];

/** Legacy broadcasts the renderer may subscribe to. */
export const SUBSCRIBABLE_CHANNELS: readonly IpcChannelName[] = [
  IpcChannel.AuthStatusChanged,
  IpcChannel.ThemeChanged,
  IpcChannel.MenuCommand,
];

/** Runtime-core invokable channels (handled by the secure bridge). */
export const RUNTIME_INVOKABLE_CHANNELS: readonly IpcChannelName[] = [
  IpcChannel.CatalogFeatured,
  IpcChannel.CatalogCollections,
  IpcChannel.CatalogSections,
  IpcChannel.CatalogSearch,
  IpcChannel.CatalogApp,
  IpcChannel.CatalogReviews,
  IpcChannel.CatalogDeveloper,
  IpcChannel.CatalogCategories,
  IpcChannel.CatalogBookmarks,
  IpcChannel.CatalogToggleBookmark,
  IpcChannel.CatalogSubmitReview,
  IpcChannel.CatalogRecommendations,
  IpcChannel.CatalogCheckUpdate,
  IpcChannel.OrgList,
  IpcChannel.OrgCreate,
  IpcChannel.OrgGet,
  IpcChannel.OrgUpdate,
  IpcChannel.OrgMembers,
  IpcChannel.OrgInvite,
  IpcChannel.OrgAcceptInvite,
  IpcChannel.OrgChangeRole,
  IpcChannel.OrgRemoveMember,
  IpcChannel.OrgWorkspaces,
  IpcChannel.OrgCreateWorkspace,
  IpcChannel.OrgUpdateWorkspace,
  IpcChannel.OrgDeleteWorkspace,
  IpcChannel.RegistryList,
  IpcChannel.RegistryGet,
  IpcChannel.RegistrySetFlags,
  IpcChannel.RegistryStats,
  IpcChannel.RegistryExport,
  IpcChannel.RegistryImport,
  IpcChannel.RegistryBackup,
  IpcChannel.NpsInstall,
  IpcChannel.NpsUninstall,
  IpcChannel.NpsUpdate,
  IpcChannel.NpsRollback,
  IpcChannel.NpsRepair,
  IpcChannel.NpsVerify,
  IpcChannel.NpsOperations,
  IpcChannel.NpsPause,
  IpcChannel.NpsResume,
  IpcChannel.NpsCancel,
  IpcChannel.RuntimeLaunch,
  IpcChannel.RuntimeStop,
  IpcChannel.RuntimeSuspend,
  IpcChannel.RuntimeResume,
  IpcChannel.RuntimeRestart,
  IpcChannel.RuntimeList,
  IpcChannel.RuntimeHealth,
  IpcChannel.PermsList,
  IpcChannel.PermsGrant,
  IpcChannel.PermsRevoke,
  IpcChannel.PluginsList,
  IpcChannel.PluginsGet,
  IpcChannel.PluginsInstall,
  IpcChannel.PluginsEnable,
  IpcChannel.PluginsDisable,
  IpcChannel.PluginsReload,
  IpcChannel.PluginsUpdate,
  IpcChannel.PluginsRemove,
  IpcChannel.PluginsGrant,
  IpcChannel.PluginsRevoke,
  IpcChannel.PluginsContributions,
  IpcChannel.PlatformEmit,
  IpcChannel.TimelineQuery,
  IpcChannel.TimelineStats,
  IpcChannel.TimelineExport,
  IpcChannel.DiagnosticsGet,
  IpcChannel.ConnectorsList,
  IpcChannel.ConnectorGet,
  IpcChannel.ConnectorStats,
  IpcChannel.ConnectorConnect,
  IpcChannel.ConnectorDisconnect,
  IpcChannel.ConnectorReconnect,
  IpcChannel.ConnectorRefresh,
  IpcChannel.ConnectorSync,
  IpcChannel.ConnectorHealthCheck,
  IpcChannel.ConnectorLogs,
  IpcChannel.ConnectorSyncState,
  IpcChannel.UnifiedQuery,
  IpcChannel.UnifiedGet,
  IpcChannel.UnifiedCounts,
  IpcChannel.UnifiedSearch,
  IpcChannel.GraphCounts,
  IpcChannel.GraphNode,
  IpcChannel.GraphNodes,
  IpcChannel.GraphNeighbors,
  IpcChannel.GraphSubgraph,
  IpcChannel.GraphPath,
  IpcChannel.GraphHistory,
  IpcChannel.GraphRebuild,
  IpcChannel.MemoryRecall,
  IpcChannel.MemoryGet,
  IpcChannel.MemoryRemember,
  IpcChannel.MemoryForget,
  IpcChannel.MemoryCounts,
  IpcChannel.MemoryRebuild,
  IpcChannel.ExecMemorySearch,
  IpcChannel.ExecMemoryForget,
  IpcChannel.ExecMemoryPin,
  IpcChannel.ExecMemoryResolve,
  IpcChannel.ExecMemoryAudit,
  IpcChannel.EnterpriseSearch,
  IpcChannel.EnterpriseTimelineQuery,
  IpcChannel.EnterpriseTimelineReplay,
  IpcChannel.EnterpriseTimelineStats,
  IpcChannel.EnterpriseTimelineExport,
  IpcChannel.BriefingGenerate,
  IpcChannel.RecommendationsGenerate,
  IpcChannel.FounderAsk,
  IpcChannel.FounderAskV2,
  IpcChannel.FounderSuggestions,
  IpcChannel.EngineeringAnalyze,
  IpcChannel.GovernanceList,
  IpcChannel.GovernanceTrace,
  IpcChannel.ContextTrace,
  IpcChannel.RelationshipTrace,
  IpcChannel.RelationshipPath,
  IpcChannel.WorkforceWorkers,
  IpcChannel.WorkforceWorkerGet,
  IpcChannel.WorkforceJobRun,
  IpcChannel.WorkforceJobs,
  IpcChannel.WorkforceJobGet,
  IpcChannel.WorkforceProposalApprove,
  IpcChannel.WorkforceProposalReject,
  IpcChannel.WorkforceWorkflowRun,
  IpcChannel.WorkforceWorkflowRuns,
  IpcChannel.WorkforceWorkflowResume,
  IpcChannel.WorkforceWorkflowCheckpoint,
  IpcChannel.WorkforceAudit,
  IpcChannel.WorkforcePolicies,
  IpcChannel.EnterpriseOrgGet,
  IpcChannel.EnterpriseOrgCreateUnit,
  IpcChannel.EnterpriseOrgUpdateUnit,
  IpcChannel.EnterpriseOrgDeleteUnit,
  IpcChannel.EnterpriseOrgCreateUser,
  IpcChannel.EnterpriseOrgUpdateUser,
  IpcChannel.EnterpriseOrgDeleteUser,
  IpcChannel.EnterpriseOrgCreateRole,
  IpcChannel.EnterpriseOrgUpdateRole,
  IpcChannel.EnterpriseOrgDeleteRole,
  IpcChannel.EnterpriseWorkspaceList,
  IpcChannel.EnterpriseWorkspaceActive,
  IpcChannel.EnterpriseWorkspaceCreate,
  IpcChannel.EnterpriseWorkspaceSwitch,
  IpcChannel.EnterpriseGraph,
  IpcChannel.EnterpriseGraphNeighbors,
  IpcChannel.EnterpriseGovernanceConfig,
  IpcChannel.EnterpriseGovernanceCompliance,
  IpcChannel.EnterpriseGovernanceSetChain,
  IpcChannel.EnterpriseGovernanceSetRule,
  IpcChannel.EnterpriseGovernanceAudit,
  IpcChannel.EnterpriseDashboard,

  // ── Ecosystem Platform ──
  IpcChannel.EcosystemDeveloperDashboard,
  IpcChannel.EcosystemDeveloperAccount,
  IpcChannel.EcosystemDeveloperSetPlan,
  IpcChannel.EcosystemKeysList,
  IpcChannel.EcosystemKeysCreate,
  IpcChannel.EcosystemKeysRevoke,
  IpcChannel.EcosystemOAuthList,
  IpcChannel.EcosystemOAuthCreate,
  IpcChannel.EcosystemOAuthDelete,
  IpcChannel.EcosystemUsageAnalytics,
  IpcChannel.EcosystemSdks,
  IpcChannel.EcosystemMarketplaceList,
  IpcChannel.EcosystemMarketplaceDetail,
  IpcChannel.EcosystemMarketplaceStats,
  IpcChannel.EcosystemMarketplaceEvents,
  IpcChannel.EcosystemListingCreate,
  IpcChannel.EcosystemVersionCreate,
  IpcChannel.EcosystemListingSubmit,
  IpcChannel.EcosystemListingReview,
  IpcChannel.EcosystemListingPublish,
  IpcChannel.EcosystemListingRollback,
  IpcChannel.EcosystemListingInstall,
  IpcChannel.EcosystemListingRate,
  IpcChannel.EcosystemGatewayVersions,
  IpcChannel.EcosystemGatewayRequest,
  IpcChannel.EcosystemGatewayAudit,
  IpcChannel.EcosystemGatewayMetrics,
  IpcChannel.EcosystemBillingSummary,
  IpcChannel.EcosystemBillingPlans,
  IpcChannel.EcosystemBillingSetPlan,
  IpcChannel.EcosystemBillingInvoice,
  IpcChannel.EcosystemBillingSeats,
  IpcChannel.EcosystemBillingAssignSeat,
  IpcChannel.EcosystemBillingReleaseSeat,
  IpcChannel.EcosystemBillingLicenses,
  IpcChannel.EcosystemBillingPurchase,
  IpcChannel.EcosystemBillingPurchases,

  // ── Enterprise Ecosystem (Stage 2) ──
  IpcChannel.EcosystemInstallsList,
  IpcChannel.EcosystemInstallsSummary,
  IpcChannel.EcosystemInstall,
  IpcChannel.EcosystemInstallUpdate,
  IpcChannel.EcosystemInstallSetEnabled,
  IpcChannel.EcosystemUninstall,
  IpcChannel.EcosystemShareWorker,
  IpcChannel.EcosystemPacksList,
  IpcChannel.EcosystemPacksStats,
  IpcChannel.EcosystemPackPublish,
  IpcChannel.EcosystemPackImport,
  IpcChannel.EcosystemPackRemove,
  IpcChannel.EcosystemPartnersList,
  IpcChannel.EcosystemPartnersStats,
  IpcChannel.EcosystemAnalytics,

  // ── Cloud Platform (Stage 1) ──
  IpcChannel.CloudRegions,
  IpcChannel.CloudTenants,
  IpcChannel.CloudTenantSummary,
  IpcChannel.CloudCreateTenant,
  IpcChannel.CloudSetTenantStatus,
  IpcChannel.CloudProjects,
  IpcChannel.CloudCreateProject,
  IpcChannel.CloudDeleteProject,
  IpcChannel.CloudTeams,
  IpcChannel.CloudCreateTeam,
  IpcChannel.CloudTenantWorkers,
  IpcChannel.CloudStorageIsolation,
  IpcChannel.CloudSsoConnections,
  IpcChannel.CloudIdentitySummary,
  IpcChannel.CloudCreateSso,
  IpcChannel.CloudUpdateSso,
  IpcChannel.CloudDeleteSso,
  IpcChannel.CloudTestSso,
  IpcChannel.CloudScim,
  IpcChannel.CloudSetScim,
  IpcChannel.CloudScimSync,
  IpcChannel.CloudMfa,
  IpcChannel.CloudSetMfa,
  IpcChannel.CloudSyncStates,
  IpcChannel.CloudSyncSummary,
  IpcChannel.CloudSyncConflicts,
  IpcChannel.CloudSyncDomain,
  IpcChannel.CloudSyncAll,
  IpcChannel.CloudSyncSetOnline,
  IpcChannel.CloudSyncRecordChange,
  IpcChannel.LiveSyncStatus,
  IpcChannel.LiveSyncNow,
  IpcChannel.LiveSyncSetOnline,
  IpcChannel.LiveSyncSetActiveOrg,
  IpcChannel.CloudDeployments,
  IpcChannel.CloudApiSummary,
  IpcChannel.CloudRatePolicies,
  IpcChannel.CloudSetPolicyEnabled,
  IpcChannel.CloudWebhooks,
  IpcChannel.CloudCreateWebhook,
  IpcChannel.CloudSetWebhookStatus,
  IpcChannel.CloudDeleteWebhook,
  IpcChannel.CloudTestWebhook,
  IpcChannel.CloudPublicApis,
  IpcChannel.CloudAdminOverview,
  IpcChannel.CloudAdminCompliance,

  // ── Federation Platform (Stage 2) ──
  IpcChannel.FedOrgs,
  IpcChannel.FedSummary,
  IpcChannel.FedInvitations,
  IpcChannel.FedInviteOrg,
  IpcChannel.FedRespondInvite,
  IpcChannel.FedTrust,
  IpcChannel.FedSetTrust,
  IpcChannel.FedShared,
  IpcChannel.FedShareResource,
  IpcChannel.FedRevokeShare,
  IpcChannel.FedArtifacts,
  IpcChannel.FedExchangeSummary,
  IpcChannel.FedPublishArtifact,
  IpcChannel.FedPublishVersion,
  IpcChannel.FedRateArtifact,
  IpcChannel.FedSetVerification,
  IpcChannel.FedRollbackArtifact,
  IpcChannel.FedInstallArtifact,
  IpcChannel.FedVerifyVersion,
  IpcChannel.FedScopeSummary,
  IpcChannel.FedSetScope,
  IpcChannel.FedPolicies,
  IpcChannel.FedGovSummary,
  IpcChannel.FedAddPolicy,
  IpcChannel.FedSetPolicyEnabled,
  IpcChannel.FedApprovals,
  IpcChannel.FedResolveApproval,
  IpcChannel.FedAuditTrail,
  IpcChannel.FedCompliance,
  IpcChannel.FedRecordAction,
  IpcChannel.FedObservability,
  IpcChannel.FedUsageSeries,
  IpcChannel.FedSecurityEvents,
  IpcChannel.FedBackups,
  IpcChannel.FedReplicas,
  IpcChannel.FedValidations,
  IpcChannel.FedContinuity,
  IpcChannel.FedDrSummary,
  IpcChannel.FedCreateBackup,
  IpcChannel.FedRunValidation,
  IpcChannel.FedCheckReplication,
  IpcChannel.FedAdminOverview,
  IpcChannel.FedScalability,
  IpcChannel.UpdateGetStatus,
  IpcChannel.UpdateCheckNow,
  IpcChannel.UpdateDownload,
  IpcChannel.UpdateInstallOnQuit,
  IpcChannel.UpdateSetChannel,
  IpcChannel.MigrationStatus,
  IpcChannel.MigrationRun,
  IpcChannel.BackupList,
  IpcChannel.BackupCreate,
  IpcChannel.BackupValidate,
  IpcChannel.BackupRestore,
  IpcChannel.BackupDelete,
  IpcChannel.CrashGetStatus,
  IpcChannel.CrashSetOptIn,
  IpcChannel.CrashExport,
  IpcChannel.CrashRecommendations,
  IpcChannel.CrashReport,
  IpcChannel.FlagsGet,
  IpcChannel.FlagsSetOverride,
  IpcChannel.FlagsClearOverride,
  IpcChannel.LicenseStatus,
  IpcChannel.LicenseRefresh,
  IpcChannel.OnboardingStatus,
  IpcChannel.OnboardingStart,
  IpcChannel.OnboardingCompleteStep,
  IpcChannel.OnboardingDismiss,
  IpcChannel.OnboardingReset,
  IpcChannel.FeedbackSubmit,
  IpcChannel.FeedbackList,
  IpcChannel.FeedbackExport,
  IpcChannel.FeedbackClear,
  IpcChannel.PilotStatus,
  IpcChannel.PilotSetEnabled,
  IpcChannel.ReleaseDiagnosticsGet,
  IpcChannel.ReleaseDiagnosticsExport,
  IpcChannel.RecoverySafeModeStatus,
  IpcChannel.RecoveryRun,
  IpcChannel.SupportGenerateBundle,
];

/** Runtime-core broadcasts. */
export const RUNTIME_BROADCAST_CHANNELS: readonly IpcChannelName[] = [
  IpcChannel.RuntimeEventBroadcast,
  IpcChannel.RuntimeOpenApp,
  IpcChannel.NpsProgress,
  IpcChannel.PluginEventBroadcast,
  IpcChannel.PlatformEventBroadcast,
  IpcChannel.ConnectorEventBroadcast,
  IpcChannel.UnifiedEventBroadcast,
  IpcChannel.GraphEventBroadcast,
  IpcChannel.MemoryEventBroadcast,
  IpcChannel.EnterpriseTimelineEventBroadcast,
  IpcChannel.WorkforceEventBroadcast,
  IpcChannel.EnterpriseEventBroadcast,
  IpcChannel.EcosystemEventBroadcast,
  IpcChannel.CloudEventBroadcast,
  IpcChannel.FedEventBroadcast,
  IpcChannel.UpdateEventBroadcast,
];

/** The full set the preload bridge permits (legacy + runtime core). */
export const ALL_INVOKABLE_CHANNELS: readonly IpcChannelName[] = [
  ...INVOKABLE_CHANNELS,
  ...RUNTIME_INVOKABLE_CHANNELS,
];

export const ALL_SUBSCRIBABLE_CHANNELS: readonly IpcChannelName[] = [
  ...SUBSCRIBABLE_CHANNELS,
  ...RUNTIME_BROADCAST_CHANNELS,
];
