apiVersion: v1
kind: Namespace
metadata:
  name: nems-prod
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nems-gateway
  namespace: nems-prod
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-name: "nems-prod-lb"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "api.neuropause033.com"
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: api-neuropause033-tls
