apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: nems-prod
spec:
  acme:
    email: neuropause033@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: nems-gateway
                namespace: nems-prod
                kind: Gateway
                group: gateway.networking.k8s.io
